### ISSUE TITLE
How to disable plugin for a particular filetype?

### ISSUE THREAD

**Issue by comfortablynick** [altermo/ultimate-autopair.nvim#11]
I looked through the docs but couldn't find this. I want to disable all pairs for some filetypes, for example `TelescopePrompt`.

Looking at the code it seems this should work, but it doesn't for me:

```lua
require("ultimate-autopair").setup {
  default_pairs = {
    ft = {
      TelescopePrompt = { disable = true },
    },
  },
}
```

It might also be handy to be able to supply a function that returns a bool which enables or disables the plugin. That would make it easier to do more complex logic with buftypes/filetypes and other factors.

**Comment by altermo** [comment]
Added the option to disable filetypes in the `ft` option and added the `TelescopePrompt={disable=true}` to the defaults.

**Comment by mawkler** [comment]
@altermo Is this still a feature? I tried adding this

```lua
require('ultimate-autopair').setup({
  default_pairs = {
    ft = {
      DressingInput = { disable = true },
    },
  },
})
```

to disable ultimate-autopair in [dressing.nvim](https://github.com/stevearc/dressing.nvim)'s input window, but it doesn't work.

I also tried browsing through the documentation and code and imitating that, but with no success.

**Comment by altermo** [comment]
It has been changed in version 0.5 to:
```lua
require('ultimate-autopair').setup({
  extensions={
    filetype={
      nft={'DressingInput'},
    },
  },
})
```

**Comment by mawkler** [comment]
@altermo Thank you, that worked for me!

Is it also possible to disable buffer types?

**Comment by altermo** [comment]
Yes:
```lua
require('ultimate-autopair').setup({
  extensions={
    cond={
      cond=function ()
        return vim.bo.buftype~='your_buffer_type'
      end,
    },
  },
})
```
