### ISSUE TITLE
Wrong behaviour deleting spaces

### ISSUE THREAD

**Issue by feekApp** [altermo/ultimate-autopair.nvim#13]
Hi,

consider the following function:
```
function(÷÷÷|'argument1', 'argument2'÷÷);
```
where `÷` is a space and `|` is the cursor position. So three spaces at start bracket and two spaces at the end bracket.

When pressing on time one the `<bs>` also the ending `'` quote of the second argument is deleted.

![](https://feek.d.pr/i/JoSXC6/2Qtfv7KfDT.gif)

Related to this, maybe you could also check if the spaces remain "balanced".

== Feek

**Comment by altermo** [comment]
Fixed.

For the "balanced" checking, is currently work in progress.

**Comment by feekApp** [comment]
Hi @altermo 

unfortunately the balanced checking is not working 100%

see movie:
![gif](https://feek.d.pr/i/HR1hwI/b13e5yEr3F.gif)

**Comment by altermo** [comment]
One line of incorrect code... Fixed.
