### ISSUE TITLE
Typo: warp vs wrap?

### ISSUE THREAD

**Issue by xulongwu4** [altermo/ultimate-autopair.nvim#16]
Hi, I see you use `fastwarp` to describe the feature where a user can move the closing parenthesis to the end of a word. This feature is usually referred to as `fastwrap`, as you can see [here](https://github.com/hrsh7th/nvim-insx#2-the-c--behaves-fast-wrapping
) and [here](https://github.com/hrsh7th/nvim-insx#2-the-c--behaves-fast-wrapping). Is that a typo in your repo?

**Comment by altermo** [comment]
No, the features which they provide are different:
In [nvim-insx](https://github.com/hrsh7th/nvim-insx) the fastwrap allows you to wrap(surround) a function(/method). At the same time, this plugin's fastwarp will enable you to warp(teleport) the ending parentheses to the next predefined separation(end of word, end of line,...).
