### ISSUE TITLE
Fly mode from inside a string

### ISSUE THREAD

**Issue by marlun** [altermo/ultimate-autopair.nvim#17]
I often use the fly mode and it works great. It doesn't work inside strings and I understand why but wonder if it would be possible to configure so that it does? In other plugins it worked and I had to do ctrl-v) to add a ')' inside a string because otherwise I would jump to the wrapping ).

If possible I would appreciate a config example. I'm guessing you could use "list_of_characters" but I'm not sure how.

**Comment by altermo** [comment]
Added a new configuration option for the extension `fly` called `nofilter` which disables filtering.

With this you can do something like:
```lua
extensions={
    --The other extensions
    {'fly',{')','}',']',' ',"'",'"',nofilter=true}},
}
```

**Comment by marlun** [comment]
Might be that these two are working against each other and I'm just not understanding but now when I'm writing normal text in markdown and I hit ' I get '' which I didn't get before. Can I get both?

**Comment by altermo** [comment]
Can you elaborate more specifically: can't reproduce glitch.

**Comment by marlun** [comment]
Before I only ran the setup function without any options:

```lua
use {
	'altermo/ultimate-autopair.nvim',
	event = { 'InsertEnter', 'CmdlineEnter' },
	config = function()
		require('ultimate-autopair').setup({
			-- extensions = {
			-- 	{ 'fly', { ')', '}', ']', ' ', "'", '"', nofilter = true } },
			-- }
		})
	end,
}
```

Now when writing in markdown files, I can write something like: `That's nice` without getting an extra `'` in the end. However when I'm in code and I have something like `require('ultimate-autopair|')` (caret at "|"), if I hit `)` I would get `require('ultimate-autopair)')` instead of jumping out: `require('ultimate-autopair')|`.

If I uncomment the option you gave me above I can jump out of `require('ultimate-autopair')` but when I write markdown I get `That''` or rather `That's nice'` because I would continue writing after the first ' but the second one would be at the end when I'm done writing.

**Comment by altermo** [comment]
Well... The current way to configure built-in extensions is stupid: When setting `extension` you overwrite the builtin extensions and thus need to include all the builtin extensions in the config (probably should fix this).
So width that in mind:
```lua
use{
    'altermo/ultimate-autopair.nvim',
    event={'InsertEnter','CmdlineEnter'},
    config=function ()
        require('ultimate-autopair').setup({
            extensions={
                {'cmdtype',{'/','?','@'}},
                'multichar',
                'string',
                {'treenode',{inside={'comment'}}},
                {'escape',{filter=true}},
                'rules',
                'filetype',
                {'alpha',{before={"'"}}},
                {'suround',{'"',"'"}},
                {'fly',{')','}',']',' ',"'",'"',nofilter=true}},
            },
        })
    end,
}
```

**Comment by marlun** [comment]
Ah, yes, that makes it a little harder BUT your above config seems to work. Thanks!

**Comment by marlun** [comment]
I'm writing in this closed issue because I'm getting the following when I'm opening neovim:

```
|| ultimate-autopair:
|| Old configuration detected
|| The problem:
|| extensions option needs updating (aborting)
|| packer.nvim: Error running config for ultimate-autopair.nvim: ...vim/lua/ultimate-autopair/configs/default/utils/init.lua:44: attempt to compare two nil values
```

Here's my current config again which you helped me with above:

```lua
require('ultimate-autopair').setup({
	extensions = {
		{ 'cmdtype',  { '/', '?', '@' } },
		'multichar',
		'string',
		{ 'treenode', { inside = { 'comment' } } },
		{ 'escape',   { filter = true } },
		'rules',
		'filetype',
		{ 'alpha',   { before = { "'" } } },
		{ 'suround', { '"', "'" } },
		{ 'fly',     { ')', '}', ']', ' ', "'", '"', nofilter = true } },
	},
})
```
