### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by tzachar** [altermo/ultimate-autopair.nvim#2]
Hi.

Cool plugin here ;)

Wonder how hard it would be to support the following features:
1) fast backwards -- the opposite of fast forward, as sometime I overshoot...
2) multi line support for fast forward -- when used at the end of line, skip to the next line.

wdyt?

**Comment by altermo** [comment]
Neither of them would be that hard to implement, will implement in version 0.3.2

**Comment by tzachar** [comment]
Cool

**Comment by tzachar** [comment]
Amazing :)
