### ISSUE TITLE
Disabling in cmd mode

### ISSUE THREAD

**Issue by alexmozaidze** [altermo/ultimate-autopair.nvim#21]
Why disable it? In Termux, there is no Del key, so you cannot do, like `"<Del>` to remove the closing quote. 

There is a workaround, and it's to use `<C-v>"` in order to insert a literal character, it gets tiring to do it sometimes, though.

**Comment by altermo** [comment]
Set the option  `cmap` to false like this:
```lua
require'ultimate-autopair'.setup{cmap=false}
```

**Comment by alexmozaidze** [comment]
Thanks for fast response! I didn't knew that c in `cmap` stood for command, could you, perhaps, add a comment in README to clarify that?
