### ISSUE TITLE
Custom characters for backspace mapping

### ISSUE THREAD

**Issue by on8t** [altermo/ultimate-autopair.nvim#22]
Hi, only issue I'm having is that I can't use ^H instead of backspace (which is very handy sometimes). However ^M instead of an actual return key works, but not ^J. I believe one way to fix that is to provide a config field for both BS and CR mappings, that will accept keys to interpret as CR or BS

```lua
{
  bs={
    lhs={'<BS>', '<C-h>'}
  },
  cr={
    lhs={'<BS>', '<C-j>'}
  }
}
```

Still a great plugin, thank you

**Comment by altermo** [comment]
Currently, this configuration option is only supported in the pre-alpha-0.5.0 version.
If you can't wait for the 0.5.0 release then you could:
```lua
vim.keymap.set('i','<C-h>',require'ultimate-autopair.maps.bs'.backspace,{expr=true})
vim.keymap.set('i','<C-j>',require'ultimate-autopair.maps.cr'.newline,{expr=true})
```

**Comment by on8t** [comment]
@altermo, thank you for the answer, will use that
I guess it isn't very different from ```:imap <c-h> <bs>```, which i was using
