### ISSUE TITLE
Error on updating plugin

### ISSUE THREAD

**Issue by feekApp** [altermo/ultimate-autopair.nvim#23]
Hi,

I  stumbled upon the following error on installing the latest version via `Lazy` on the nightly build of neovim:

```
 error: Your local changes to the following files would be overwritten by checkout:
 doc/tags
 Please commit your changes or stash them before you switch branches.
```

== Feek

**Comment by altermo** [comment]
Hi,
I don't know the exact cause, but I would guess that you have a plugin/vim option set that auto-generated a doc/tags file and overwrites the original one, causing git to throw an error about saving changes.
The simplest solution is to reinstall the plugin (that's what I do whenever I encounter this issue).

**Comment by feekApp** [comment]
mmm,
I'am not aware of an auto generating doc/tags option... I'll dive into this. Reinstalling does not help.

**Comment by altermo** [comment]
My last idea is to delete the plugin completely:
```fish
rm -r $HOME/.local/share/nvim/lazy/ultimate-autopair.nvim
```

**Comment by feekApp** [comment]
Already did this! Installing goes well, But on checking on updates again (pressing U in Lazy) the error  occurs again.

**Comment by altermo** [comment]
Reading the lazy.nvim source code:
There's a file called lazy-lock.json which contains information about plugins, remove the line about ultimate-autopair.nvim and then do the previously stated step (deleting the plugin completely).

**Comment by feekApp** [comment]
Thnx @altermo this fixed the issue! 👍

== Feek
