### ISSUE TITLE
Curious about commit messages

### ISSUE THREAD

**Issue by marlun** [altermo/ultimate-autopair.nvim#25]
Hi,

I've been using ultimate-autopair and it's working great for me. I like to follow the work by reading commit messages but it's very hard the way It's done in this project. The commit message is just the files which were changed I believe? Is it not hard even for you to go back and see what's been done?

**Comment by altermo** [comment]
Well if other people are interested in the commit messages, then I will gladly write commit messages with detail.

**Comment by wookayin** [comment]
+100. And standard coding conventions (style, formatting, etc.) too. Thank you for accepting such requests.
