### ISSUE TITLE
Newline <BS> doesn't work?

### ISSUE THREAD

**Issue by asyncedd** [altermo/ultimate-autopair.nvim#27]
Hey, thanks for this awesome plugin!

FYI, Newline <BS> doesn't work from this commit: 036b8c1d2543a5e00f9ee7f13bfaf5b188d27123

Minimal repro:
```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  -- do not remove the colorscheme!
  "folke/tokyonight",
  -- add any other pugins here
  {
    "altermo/ultimate-autopair.nvim",
    opts = {
      bs = {
	enable = true,
      },
    },
    commit = "f92801d",
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here
vim.opt.termguicolors = true
-- do not remove the colorscheme!
vim.cmd([[colorscheme tokyonight]])
```

Run with:
```bash
nvim -u repro.lua repro.lua
```

**Comment by altermo** [comment]
The reason that newline backspace changed was that sometimes one wants to delete indentation and not activate newline backspace, but if you want old behaviour:
Added back old style newline backspace with the option `{bs={indent_ignore=true}}`. ([dace596](https://github.com/altermo/ultimate-autopair.nvim/commit/dace596dce638f2b60b868cf601cbf8f9e117cb6))

**Comment by asyncedd** [comment]
Hey, sorry but I believe that it's still not working like before?

**Comment by altermo** [comment]
Can you give a precise description of what is not working, as I still don't know what the exact problem is?

**Comment by asyncedd** [comment]
Sorry for misunderstanding, so, the problem is that, I want to newline backspace but, it still doesn't (even on the commit you've provided)

What I mean is:

What I wanted (Before 036b8c1d2543a5e00f9ee7f13bfaf5b188d27123 worked btw)
```lua
{
  |
}
```
`<BS>`
```lua
{|}
```

And what is happening is:
```lua
{
  |
}
```
`<BS>`
```lua
{
|
}
```

Also, it is happening WITH
```lua
{
  bs = {
    indent_ignore=true
  }
}
```

I'm sorry if there misunderstandings but, I hope it makes sense

**Comment by altermo** [comment]
Try updating to branch [dace596](https://github.com/altermo/ultimate-autopair.nvim/commit/dace596dce638f2b60b868cf601cbf8f9e117cb6).

**Comment by asyncedd** [comment]
Sorry for the delay but, I've updated to commit 5ace596, and the issue still persists

**Comment by altermo** [comment]
Hmm… There might be a different problem, cause I tested with minimal config (and it worked):
<details>
<summary>The minimal config</summary>

```lua
local root = vim.fn.fnamemodify("./.repro", ":p")

-- set stdpaths to use .repro
for _, name in ipairs({ "config", "data", "state", "cache" }) do
  vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

-- bootstrap lazy
local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "--single-branch",
    "https://github.com/folke/lazy.nvim.git",
    lazypath,
  })
end
vim.opt.runtimepath:prepend(lazypath)

-- install plugins
local plugins = {
  -- do not remove the colorscheme!
  "folke/tokyonight.nvim",
  -- add any other pugins here
  {
    "altermo/ultimate-autopair.nvim",
    opts = {
      bs = {
        enable = true,
        indent_ignore = true,
      },
    },
    commit = "dace596",
  },
}
require("lazy").setup(plugins, {
  root = root .. "/plugins",
})

-- add anything else here
vim.opt.termguicolors = true
-- do not remove the colorscheme!
vim.cmd([[colorscheme tokyonight]])
```
</details>

Try:
1. Remove `ultimate-autopair.nvim` from lazy install list
2. Clean lazy (so that `ultimate-autopair.nvim` is completely removed)
3. Add `ultimate-autopair.nvim` back to lazy install list
