### ISSUE TITLE
health error

### ISSUE THREAD

**Issue by mathjiajia** [altermo/ultimate-autopair.nvim#28]
Below is the output of `checkhealth`:

ultimate-autopair
- `tests starting`
- `ERROR error while checking health: Vim:E903: Process failed to start: too many open files: "/usr/local/bin/nvim"`

**Comment by mathjiajia** [comment]
But I still got the same error massage.

**Comment by altermo** [comment]
Ok, set the limit even lower.
(If it doesn't work then clean install the plugin and try again)

**Comment by mathjiajia** [comment]
Solved.
