### ISSUE TITLE
[help] how to config ultimate-autopair.nvim for my special use case in lisp file

### ISSUE THREAD

**Issue by rhcher** [altermo/ultimate-autopair.nvim#29]
First of all, thank you for this great plugin for neovim, It't the best autopair plugin that I have used. This issue is more about help than issue.

### what I meet
As a [fennel](https://fennel-lang.org/) man, I use [parinfer-rust](https://github.com/eraserhd/parinfer-rust) as my auto-pairs plugin in all lisp buffer, it solves all things related to bracket balancing but quotation marks. So, the problem is there is little confilicts between ulitmate-autopair.nvim and parinfer-rust. For example:

1. this is a fennel buffer
![image](https://github.com/altermo/ultimate-autopair.nvim/assets/50723480/a5755733-69f8-4787-b845-f81aa9399cce)
2. than I input `enter`
![image](https://github.com/altermo/ultimate-autopair.nvim/assets/50723480/3a9ca808-0a09-47a0-a1e9-3ca6a30eac8f)
that because parinfer-rust auto balance bracket and break autopairs' `cr` function

### several solutions

1. Disable all bracket related function only in lisp buffer(and I would like to keep the quoted functions), but I don't know how to do it. Maybe let `cr` enable can be a function and I can add some logic in it
2. Or provider a buffer level configuration and I can call it in filetype autocmd.

**Comment by altermo** [comment]
Ok, I've added an option called `extension.rules.rules` which can create config global rules ([cc4e8dc](https://github.com/altermo/ultimate-autopair.nvim/tree/cc4e8dc9f296f1fd2c6a6d3c359ae90f07d104c4)).
So now you can just:
```lua
{
  extensions={
    rules={rules={{'not',{'option','lisp'}}}},
    --rules option uses lisp style syntax
  },
}
```
<details>
<summary>A more complicated solution, (if you wish to use an older version of the plugin)</summary>

```lua
local ua=require'ultimate-autopair'
local default=require'ultimate-autopair.default'
local conf=vim.tbl_extend('force',default,{
  --your config goes here.
})
ua.add_conf({
  config_type='cond',
  rule=function () --use `check=function ()` if before commit(956715f)
    return not vim.o.lisp
  end,
  conf,
})
```
</details>

**Comment by rhcher** [comment]
sorry, I still can't make it work, it too complex to me, what I want in fennel file is just: 
1. disable bracket related function (like () [] {} and `cr`)
2. keep quote auto pair work

**Comment by altermo** [comment]
(First: Update to the latest release)
Currently, there's no way to do this using the pairing API (it's a work in progress).
So one needs to use the core API and a lot of copy-pasting from default:
```lua
local ua=require'ultimate-autopair'
local default=require'ultimate-autopair.default'
ua.add_conf(
  vim.tbl_extend('force',default.conf,{
    config_type='default',
    internal_pairs=false,
    {'"','"',suround=true,string=true,fastwarp=true},
    {"'","'",suround=true,rules={{'when',{'option','lisp'},{'instring'}}},alpha=true,nft={'tex'},string=true,fastwarp=true},
    {'`','`',nft={'tex'},fastwarp=true},
    {'string',type='tsnode',string=true},
    {'raw_string',type='tsnode',string=true},
  }))
local conf=vim.tbl_extend('force',default.conf,{
  --your config goes here.
})
ua.add_conf({
  config_type='cond',
  rule=function ()
    return not vim.o.lisp
  end,
  conf,
})
ua.init()
```

**Comment by rhcher** [comment]
Hi, thank you for your help. But I found that this plugin already has a very elegant way to meet my needs:
```lua
ua.setup({ cr = {conf = {nft = util["lisp-language"]}},
           bs = {conf = {nft = util["lisp-language"]}}})
```
