### ISSUE TITLE
Feature Request: Command to Enable/Disable

### ISSUE THREAD

**Issue by windowsrefund** [altermo/ultimate-autopair.nvim#30]
Hello,

Really enjoying this plugin and wonder if there are plans to offer something along the lines of a `:UAEnable` and `:UADisable` which could then be mapped as needed?

**Comment by altermo** [comment]
Ok, added an option to disable core ([`c627492`](https://github.com/altermo/ultimate-autopair.nvim/commit/c62749291d71f7a22c465fda62c457cc1434281e)).
Use: `require'ultimate-autopair.core'.disable=true`

**Comment by windowsrefund** [comment]
Can I ask for this to be revisited as an actual toggle would be far more practical. As it stands now, it feels like some amount of code would need to be written in order to determine what to set (true or false). So the real utility of this functionality would come in the form of `:UAToggle` or `require('ultimate-autopair.core').toggle()`
