### ISSUE TITLE
How to disable in comments?

### ISSUE THREAD

**Issue by windowsrefund** [altermo/ultimate-autopair.nvim#31]
Is this even possible?

Thanks in advance

**Comment by altermo** [comment]
First, update to the latest release.
Second:
```lua
require'ultimate-autopair'.setup({
  extensions={
    rules={rules={{'call',function(o)
      return o.col==1 or vim.treesitter.get_node({pos={o.linenr-1,o.col-2}}):type()~='comment'
    end
    }}}
  }
})
```

**Comment by windowsrefund** [comment]
Thank you. I just updated to `c17f0731db05f2a733b382718b91e0873683ed1b`

```...s/neovim/0.9.0/share/nvim/runtime/lua/vim/treesitter.lua:121: There is no parser available for buffer 1 and one could not be created because lang could not be determined. Either pass lang or set the buffer filetype
stack traceback:
	...y/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:104: in function <...y/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:99>
	[C]: in function 'error'
	...s/neovim/0.9.0/share/nvim/runtime/lua/vim/treesitter.lua:121: in function 'get_parser'
	...s/neovim/0.9.0/share/nvim/runtime/lua/vim/treesitter.lua:398: in function 'get_node'
	...e/akosmin/.config/nvim/lua/plugins/ultimate-autopair.lua:15: in function 'check_rule'
	...autopair.nvim/lua/ultimate-autopair/extensions/rules.lua:54: in function 'check_rules'
	...autopair.nvim/lua/ultimate-autopair/extensions/rules.lua:73: in function <...autopair.nvim/lua/ultimate-autopair/extensions/rules.lua:69>
	[C]: in function 'xpcall'
	...y/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:121: in function <...y/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:120>
	...zy/ultimate-autopair.nvim/lua/ultimate-autopair/core.lua:40: in function <...zy/ultimate-autopair.nvim/lua/ultimate-autopair/core.lua:32>
```

Here's my config

```return {
  {
    'altermo/ultimate-autopair.nvim',
    enabled = true,

    event = { 'InsertEnter', 'CmdlineEnter' },
    config = function()
      require('ultimate-autopair').setup({
        -- Disable autopair in the command line: https://github.com/altermo/ultimate-autopair.nvim/issues/8
        cmap = false,
        extensions = {
          rules = {
            rules = { { 'call', function(o)
              return o.col == 1 or vim.treesitter.get_node({ pos = { o.linenr - 1, o.col - 2 } }):type() ~= 'comment'
            end
            } }
          },
          filetype = {
            p = 80,
            nft = {
              'TelescopePrompt',
              'text',
            },
          },
          -- Get Fly Mode working on strings: https://github.com/altermo/ultimate-autopair.nvim/issues/17
          fly = {
            nofilter = true,
          },
        },
        { '"', '"', fly = true, p = 11 },
        { "'", "'", fly = true, p = 11 },
      })
    end
  },
}
```

**Comment by altermo** [comment]
Oh sorry, I forgot to check if there's a treesitter parser for the buffer, or if were in cmdline...
In that end use:
```lua
require'ultimate-autopair'.setup({
  extensions={
    rules={rules={{'call',function(o)
      return o.cmdline
        or not vim.treesitter.language.get_lang(vim.o.filetype)
        or o.col==1
        or vim.treesitter.get_node({pos={o.linenr-1,o.col-2}}):type()~='comment'
    end
    }}}
  }
})
```

**Comment by altermo** [comment]
Oh sorry, I forgot to check if tressitter parser is attached to the buffer, or if in cmd line mode.
In that end use:
```lua
require'ultimate-autopair'.setup({
  extensions={
    rules={rules={{'call',function(o)
      return o.incmd
        or o.col==1
        or not pcall(vim.treesitter.get_node,{pos={o.linenr-1,o.col-2}})
        or vim.treesitter.get_node({pos={o.linenr-1,o.col-2}}):type()~='comment'
    end
    }}}
  }
})
```

**Comment by windowsrefund** [comment]
Surprisingly, the first one works as expected while the 2nd (with the `pcall` is just ignored).

**Comment by altermo** [comment]
So, is your problem solved?
If not, pleas describe in more detail what you want.

**Comment by windowsrefund** [comment]
I thought my last message made it perfectly clear neither solution solves the problem. With all due respect, are you testing this as you go?

**Comment by altermo** [comment]
Can you please describe in more detail what you want?

**Comment by altermo** [comment]
That's what I don't understand, the example 2 I gave disables auto-pairing (and all other features) when inserting inside comments.

**Comment by windowsrefund** [comment]
Interesting. It's working like a charm now and I'm not seeing the results I posted last night. Looks like we've got a winner here. Thanks again for providing this. This, along with being able to 'jump', are my favorite features of this solution.

**Comment by windowsrefund** [comment]
Just wanted to thank you again and explain something I just picked up on which helps me to now understand why I wasn't seeing consistent results. 

Scenario 1: I am on any line in a .lua file and type `o`. On the new line, I type `--` to begin a comment and then type any character that would normally autopair.

Scenario 2: I am on any line in a .lua file and type `gco`to get dropped into a new line that is already commented (This is a mapping provided by Comment.nvim). In the now already commented line, I type any character that would normally autopair.

Scenario 3: In an already commented line, I type any character that would normally autopair.

Results:
Scenario 1:  Fail, the character autopairs.

Scenario 2: Pass, the character does not autopair

Scenario 3: Pass, the character does not autopair

I suppose this has to do with deeper level treesitter stuff I don't quite grok and the solution provided is more than acceptable since I do try to make use of `gco` and `gcO` when I know I want to add comments. Just wanted to leave this here for anyone who goes down this particular road and may be confused about the results.

All the best.
