### ISSUE TITLE
Rule from #31 not working with markdown files

### ISSUE THREAD

**Issue by windowsrefund** [altermo/ultimate-autopair.nvim#32]
I suspect this is related to the enhancement provided in #31 where the plugin is configured to avoid autopairing in comments.

How to reproduce:
1. Add rule mentioned above.
2. Open a new .md file
3. Attempt to add a valid Markdown header like `##Something`

```
...e/windowsrefund/.config/nvim/lua/plugins/ultimate-autopair.lua:27: attempt to index a nil value
stack traceback:
	...y/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:104: in function '__index'
	...e/windowsrefund/.config/nvim/lua/plugins/ultimate-autopair.lua:27: in function 'check_rule'
	...autopair.nvim/lua/ultimate-autopair/extensions/rules.lua:54: in function 'check_rules'
	...autopair.nvim/lua/ultimate-autopair/extensions/rules.lua:73: in function <...autopair.nvim/lua/ultimate-autopair/extensions/rules.lua:69>
	[C]: in function 'xpcall'
	...y/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:121: in function <...y/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:120>
	...zy/ultimate-autopair.nvim/lua/ultimate-autopair/core.lua:40: in function <...zy/ultimate-autopair.nvim/lua/ultimate-autopair/core.lua:32>
```

Curious to hear your thoughts and/or answer any questions.

**Comment by altermo** [comment]
Can you please give me the contents of your config file containing the auto-pair config, or at least line 27?

**Comment by windowsrefund** [comment]
Happy to report I appear to have solved this by identifying and removing a piece of the config that was leaning into `core.disable`. Something I believe I was testing but never fleshed out. My guess is that it may have created the race condition against the rule mentioned in #31. That said, it's now interesting to see that a markdown comment is not qualifying against the rule and as a result, pairing still works (which is counter to the objective of the anti-comment rule previously mentioned).

Here's my current config

```
return {
  {
    'altermo/ultimate-autopair.nvim',
    enabled = true,

    event = { 'InsertEnter', 'CmdlineEnter' },
    config = function()
      require('ultimate-autopair').setup({
        -- Disable autopair in the command line: https://github.com/altermo/ultimate-autopair.nvim/issues/8
        cmap = false,
        extensions = {
          rules = {
            rules = { { 'call', function(o)
              return o.incmd
                  or o.col == 1
                  or not pcall(vim.treesitter.get_node, { pos = { o.linenr - 1, o.col - 2 } })
                  or vim.treesitter.get_node({ pos = { o.linenr - 1, o.col - 2 } }):type() ~= 'comment'
            end
            } }
          },
          filetype = {
            p = 80,
            nft = {
              'TelescopePrompt',
              'text',
            },
          },
          -- Get Fly Mode working on strings: https://github.com/altermo/ultimate-autopair.nvim/issues/17
          fly = {
            nofilter = true,
          },
        },
        { '"', '"', fly = true, p = 11 },
        { "'", "'", fly = true, p = 11 },
      })
    end
  },
}
```

Now, I open a .md file, press `gco` to insert a new comment and from within the newly added comment, type `'` or any character this plugin normally pairs. The expectation here is that pairing should not occur. However, it does. Worth noting is the markdown treesitter parser is installed.

**Comment by altermo** [comment]
There are 2 different unrelated problems:
1. The error is caused by the fact that `vim.treesitter.get_node` can return nil (sorry about not checking)

<details>
<summary>Corrected version of config</summary>

```lua
require'ultimate-autopair'.setup({
  extensions={
    rules={rules={{'call',function(o)
      local status,node=pcall(vim.treesitter.get_node,{pos={o.linenr-1,o.col-2}})
      return o.incmd
        or o.col==1
        or not status
        or not node
        or node:type()~='comment'
    end
    }}}
  }
})
```
</details>

2. Markdown comments have the tsnode-type `html_block` and not `comment`

<details>
<summary>Config which contains to disable in `html_block` (NOTE: may cause some incorrectness, but generally works)</summary>

```lua
require'ultimate-autopair'.setup({
  extensions={
    rules={rules={{'call',function(o)
      local status,node=pcall(vim.treesitter.get_node,{pos={o.linenr-1,o.col-2}})
      return o.incmd
        or o.col==1
        or not status
        or not node
        or node:type()~='comment' and node:type()~='html_block'
    end
    }}}
  }
})
```
</details>

**Comment by windowsrefund** [comment]
Very interesting. I'll close this out tonight once I get a chance to incorporate. Thank you.

**Comment by windowsrefund** [comment]
Working quite nicely over here. Thanks again. I can't help but wonder if these (now) known patterns might find their way into feature flippers at some point. Something along the lines of a boolean like `disable_comments = true` or something at a higher level. While obviously very powerful, I just don't know how likely it is that non programmers are going to be able to fully leverage `rules`  in order to carve out these bits of functionality as needs arise over time. Just something to think about. Thank you once again!

**Comment by altermo** [comment]
From your suggestion of creating something that makes disabling inside comments easier, I created the extension `tsnode` which can disable inside/outside of ts-nodes.
To disable inside comments:
```lua
require'ultimate-autopair'.setup({
  extensions={
    tsnode={outside={'comment'},p=50},
}})
```
