### ISSUE TITLE
Fly mode in newer version of ultimate-autopair

### ISSUE THREAD

**Issue by marlun** [altermo/ultimate-autopair.nvim#33]
I wrote in a closed issue #17 but thought I'd write a new one since the message might be missed when it's in a closed issue. In #17 you helped me setting up fly mode however in the new version it stopped working and I'm getting

```
|| ultimate-autopair:
|| Old configuration detected
|| The problem:
|| extensions option needs updating (aborting)
|| packer.nvim: Error running config for ultimate-autopair.nvim: ...vim/lua/ultimate-autopair/configs/default/utils/init.lua:44: attempt to compare two nil values
```

Here's my current config again which you helped me with above:

```lua
require('ultimate-autopair').setup({
	extensions = {
		{ 'cmdtype',  { '/', '?', '@' } },
		'multichar',
		'string',
		{ 'treenode', { inside = { 'comment' } } },
		{ 'escape',   { filter = true } },
		'rules',
		'filetype',
		{ 'alpha',   { before = { "'" } } },
		{ 'suround', { '"', "'" } },
		{ 'fly',     { ')', '}', ']', ' ', "'", '"', nofilter = true } },
	},
})
```
This worked great before and would really appreciate getting it working with the new version. There's no hurry though.

**Comment by altermo** [comment]
First, update to the newest version. ([`d31cc98`](https://github.com/altermo/ultimate-autopair.nvim/commit/d31cc988cd1ddf3f9918f2d938d1e7978be949ea))
Second:
```lua
require('ultimate-autopair').setup({
  extensions={fly={nofilter=true}},
  config_internal_pairs={
    {'"','"',fly=true},
    {"'","'",fly=true},
  },
})
```

**Comment by marlun** [comment]
Thanks for listening and adding support!
