### ISSUE TITLE
Revisit the request for a toggle

### ISSUE THREAD

**Issue by windowsrefund** [altermo/ultimate-autopair.nvim#35]
Hello,

Can I ask for #30 to be revisited as an actual toggle would be far more practical. As it stands now, it feels like some amount of code would need to be written in order to determine what to set (true or false). So the real utility of this functionality would come in the form of :UAToggle or require('ultimate-autopair.core').toggle(). If a toggle were made available, one would be able to assign it to a single keymap in order to easily change state.

**Comment by altermo** [comment]
Ok, as for your suggestion, added `require'ultimate-autopair'.toggle()` ([638d2fe](https://github.com/altermo/ultimate-autopair.nvim/commit/638d2fecdd59e9636b97f906508b5a54274af67e))

**Comment by windowsrefund** [comment]
Thank you!

**Comment by windowsrefund** [comment]
Thanks again for supplying this. I just PR'd https://github.com/AstroNvim/astrocommunity/pull/314 which uses this.
