### ISSUE TITLE
Can't tab twice?

### ISSUE THREAD

**Issue by 9mm** [altermo/ultimate-autopair.nvim#36]
Make a new file

    :setf ruby

and type:

    hello['|']

and hit tab twice, and it stops after ' but doesnt go to ]

I notice SOME times it works on lua, but not always, and it seems to sometimes work elsewhere, but I can't figure out what exactly causes it.

**Comment by altermo** [comment]
I can't figure out what you mean.
The only thing I get is that you're using tabout, which is currently "experimental", and that is why the doc is incorrect about it, as it does not jump out of pairs but works similarly to [tabout.nvim](https://github.com/abecodes/tabout.nvim).

**Comment by 9mm** [comment]
Ah my mistake... I forgot I had added that 🤦🏻‍♂️

Sorry... I have been staring at my vim config for literally like 10 hours trying to sort all these stupid minor pains out...

Ill make an issue with tabout or go look at their config docs
