### ISSUE TITLE
Bug: Crashes nvim when a bracket is typed

### ISSUE THREAD

**Issue by chrisgrieser** [altermo/ultimate-autopair.nvim#39]
When I pass anything in the setup call, it completely crashes nvim as soon as I type a bracket the first or second time.

Reproducible with minimal config:
```lua
local plugins = {
	{
		"altermo/ultimate-autopair.nvim",
		event = { "InsertEnter", "CmdlineEnter" },
		dependencies = "nvim-treesitter/nvim-treesitter",
		opts = {},
	},
}
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system {
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable",
		lazypath,
	}
end
vim.opt.runtimepath:prepend(lazypath)
require("lazy").setup(plugins)
```

```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3
macOS 13.4.1
```

**Comment by altermo** [comment]
Can't reproduce.
When you say crash, do you mean crash or freeze, and if crash, with what error code?

**Comment by chrisgrieser** [comment]
Completely crash, no error message of any kind. Or at least none that I could see, since it crashes instantly.

**Comment by altermo** [comment]
I mean the $status error code that is set after an app has an error in the shell.
Also, try it without nvim-treesitter.

**Comment by chrisgrieser** [comment]
Ah, yes. It's exit code 139 with no further message showing up in the terminal. Tried without treesitter, makes no difference.

I tested this a bit, and as far as I can tell, with a new file. But if there is some content in the file already, it happens in the first few brackets typed. Though the exact number depends apparently on the note content.

The minimal test file (used with the minimal config) is this one:

```lua
require("foobar").supports_method("foobar")

```

Open this file with the minimal config from above, go to the second line, type `(` 9 times, it crashes with 139.

**Comment by altermo** [comment]
I might have an idea of what's happening.
Try out:
```lua
local plugins = {
	{
		"altermo/ultimate-autopair.nvim",
		event = { "InsertEnter", "CmdlineEnter" },
		dependencies = "nvim-treesitter/nvim-treesitter",
		opts = {},
                commit = "667d2304e8eb9ddbfa7f962528cfce0a5edcc163"
	},
}
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system {
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable",
		lazypath,
	}
end
vim.opt.runtimepath:prepend(lazypath)
require("lazy").setup(plugins)
```

**Comment by chrisgrieser** [comment]
yep, that commit fixes it!

**Comment by altermo** [comment]
Then it has something to do with [#24783](https://github.com/neovim/neovim/issues/24783) as it is in the commit after that the plugin started using TSNode:tree().
I would recommend staying at that commit if you're not planning to update neovim.

**Comment by chrisgrieser** [comment]
and if I do plan to update nvim?

**Comment by altermo** [comment]
Then if you update to a version after the neovim pull request [24769](https://github.com/neovim/neovim/pull/24796) then it won't crash, and you can just use the main version of the plugin.

**Comment by sainttttt** [comment]
> ```lua
> 	{
> 		"altermo/ultimate-autopair.nvim",
> 		event = { "InsertEnter", "CmdlineEnter" },
> 		dependencies = "nvim-treesitter/nvim-treesitter",
> 		opts = {},
>                 commit = "667d2304e8eb9ddbfa7f962528cfce0a5edcc163"
> 	},
> ```

Just FYI I am also having this same issue in nvim 0.9.1 and this fixes it for the time being. I tried installing the current nvim --HEAD from homebrew but it's not installing for whatever reason, so I'm using this for the time being. Thanks!
