### ISSUE TITLE
enter key doesn't work in insert mode

### ISSUE THREAD

**Issue by aj3423** [altermo/ultimate-autopair.nvim#41]
This is my config:
```
	{
		'altermo/ultimate-autopair.nvim',
		event={'InsertEnter','CmdlineEnter'},
		branch='v0.6',
		opts={
			--Config goes here
		},
	},
```
In insert mode, press Enter key, nothing happens.

**Comment by altermo** [comment]
Can you provide a minimal config?

**Comment by aj3423** [comment]
@altermo  I find it conflicts with the plugin:
```
	{
		'tpope/vim-eunuch', config = function ()
			vim.cmd('cnoreabbrev rename Rename')
		end
	}, 
```
It's for renaming file, I searched for 'enter' in its source code and found: 
https://github.com/tpope/vim-eunuch/blob/master/plugin/eunuch.vim#L502-L505

Is this conflict fixable? If not, I'll try to find another way to rename file.

**Comment by wookayin** [comment]
This happens quite often for me. I'm pretty sure it has nothing to do with vim-enunch.

In my case `<CR>` (the enter key) seems to be in conflict with nvim-cmp which also requires imap `<CR>`. 

```
i  <CR>        * <Lua 433: ~/.vim/plugged/nvim-cmp/lua/cmp/utils/keymap.lua:127>
                 cmp.utils.keymap.set_map
```

**Comment by altermo** [comment]
cmp-nvim is smart, are you using fallback in your map like this:
```lua
['<CR>']=cmp.mapping(function(fallback)
  if cmp.get_active_entry() then
    cmp.confirm()
  else
    fallback() --fallbacks to previously defined map
  end
end)
```

**Comment by wookayin** [comment]
I thought I had, but it wasn't.

The following is the suggested keymap by nvim-cmp ([README](https://github.com/hrsh7th/nvim-cmp#setup)):

```
      ['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently
```

so I guess many users will have `<CR>` key conflicting unless they have the fallback mechanism set. It would be great to leave some documentation somewhere in your README.

**Comment by altermo** [comment]
For the vim-enough, you can set `g:eunuch_no_maps` ([source code](https://github.com/tpope/vim-eunuch/blob/master/plugin/eunuch.vim#L474)).
But yeah, I shall add it to the README.

**Comment by aj3423** [comment]
@altermo Thanks, that works, now the Enter works fine.
```
	{
		'tpope/vim-eunuch', config = function ()
			vim.g.eunuch_no_maps = true
		end
	},
```

**Comment by aj3423** [comment]
@wookayin I also have cmp enabled, and also have this line:
```
		['<CR>'] = cmp.mapping.confirm({ select = true }), -- Accept currently selected item. Set `select` to `false` to only confirm explicitly selected items.
```
And it works fine. 
In my case it's the vim-enunch that causes the problem, I have minimal vimrc that contains only two plugins enabled which are ultimate-autopair and vim-enunch, it still conflicts. Do you have vim-enunch installed?

**Comment by wookayin** [comment]
Yes I also have vim-enunch installed. Thanks for pointing that out. Interesting, I didn't know that vim-enunch also sets up an insert-mode keymap for <CR> until I read its source code today, as the plugin seemed to provide "unix-like commands". It's just for auto-completing shebang?

I'm not very sure what exactly makes the CR key broken, but this bug isn't always reproducible.  It sometimes works but it's broken sometimes. I think the bug lies in ultimate-autopair; in theory if there are another imap `<CR>`, we can still have a conflict -- it might be vim-eunuch but it could be nvim-cmp.

**Comment by altermo** [comment]
I see the problem, global values should be set before loading the plugin, but the config= runs after the plugin is loaded. Use init= instead.
Here's a minimal config that worked:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
require'lazy'.setup{
    {'altermo/ultimate-autopair.nvim',opts={}},
    {'tpope/vim-eunuch',init=function()
        vim.g.eunuch_no_maps=true
    end},
}
```

**Comment by altermo** [comment]
Update: I refactored the code so that the crash doesn't happen anymore on older neovim versions.
