### ISSUE TITLE
Conflict with nvim-treesitter-endwise

### ISSUE THREAD

**Issue by wookayin** [altermo/ultimate-autopair.nvim#42]
Reproduce:

```lua
for name, url in pairs{
  treesitter = 'nvim-treesitter/nvim-treesitter',
  endwise = 'RRethy/nvim-treesitter-endwise',
  autopair = 'altermo/ultimate-autopair.nvim',
} do
  local install_path = vim.fn.fnamemodify('nvim_issue/'..name, ':p')
  if vim.fn.isdirectory(install_path) == 0 then
    print(vim.fn.system { 'git', 'clone', '--depth=1', 'https://github.com/' .. url, install_path })
  end
  vim.opt.runtimepath:append(install_path)
end

require "ultimate-autopair".setup {}

require "nvim-treesitter.configs".setup {
  endwise = { enable = true }
}
```

```
$ nvim -u minimal.lua foo.lua
```

and type `(function()` followed by `<CR>`.

Actual Result: two `end`s are inserted.

```
(function()
   |
end
end
  )
```

Expected:

```
(function()
   |
end)
```

**Comment by altermo** [comment]
Fixed; the problem was that nvim-treesitter takes all `\r` inputs, and uses them, so I replaced all but one with `\n`.
The problem of the `end` going onto a different line than the `)` I don't know how to fix.

**Comment by wookayin** [comment]
Thanks, after 7b87d62d05239d5d5356767f7deccf6181b0acaa (BTW it'd be good to add a reference to an issue in the commit message so that they can be linked), now it works like:

```
(function()
   |
end
  )
```

The issue of `)` being placed in the following line and with an unexpected indent would need some more investigations. I'm not sure which of the endwise and autopair plugin is mainly responsible for this, but seems tricky to fix.

**Comment by altermo** [comment]
Okay, I have **hacked** together a solve for anyone to use.
Note: I fixed a few in the plugin so please update to the latest release
```lua
local linecount
require'ultimate-autopair'.init{
  require'ultimate-autopair'.extend_default(your_own_config),
  {
    profile='map',
    p=11,
    {'i','\r',function ()
      linecount=vim.api.nvim_buf_line_count(0)
    end}
  }
}
vim.api.nvim_create_autocmd('User',{pattern='PreNvimTreesitterEndwiseCR',callback=function()
  if not linecount then return end
  if linecount+1==vim.api.nvim_buf_line_count(0) then
    linecount=nil
  else
    linecount=vim.api.nvim_buf_line_count(0)
  end
end})
vim.api.nvim_create_autocmd('User',{pattern='PostNvimTreesitterEndwiseCR',callback=function()
  if not linecount then return end
  if linecount~=vim.api.nvim_buf_line_count(0) then
    vim.cmd.norm{bang=true,'jJk'}
  end
  linecount=nil
end})
```

**Comment by altermo** [comment]
Okay, implemented integration: https://github.com/altermo/ultimate-autopair.nvim/commit/9dfbe28cd6ec34f234543a9abbfe8be6906b92f6
