### ISSUE TITLE
[bug] crash nvim

### ISSUE THREAD

**Issue by kaiphat** [altermo/ultimate-autopair.nvim#43]
I works only when plugin is enabled.
Steps in lua file:
1. type `M.get`
2. type `(`
3. try to remove (tap backspace). Sometimes crash was right here.
4. try to type later `_langu` -> CRASH

**Comment by altermo** [comment]
It has to do with neovim bug [#24783](https://github.com/neovim/neovim/issues/24783); use commit [667d230](https://github.com/altermo/ultimate-autopair.nvim/commit/667d2304e8eb9ddbfa7f962528cfce0a5edcc163) if your not planing to update neovim.

**Comment by altermo** [comment]
Update: I refactored the code so that the crash doesn't happen anymore on older neovim versions.
