### ISSUE TITLE
Why did neovim crashes?

### ISSUE THREAD

**Issue by altermo** [altermo/ultimate-autopair.nvim#44]
Neovim crashed because of a neovim bug [#24783](https://github.com/neovim/neovim/issues/24783) which has been fixed, but requires neovim to be updated to the latest dev version.
If you're not planning to update neovim, then install the plugin with the commit [667d230](https://github.com/altermo/ultimate-autopair.nvim/commit/667d2304e8eb9ddbfa7f962528cfce0a5edcc163).

# Update
I have refactored the code so that the crash won't happen, at the cost of speed.
You can now use the latest release of the plugin without worry.

**Comment by altermo** [comment]
Note that I have refactored the code to not crash because of neovim, you can now use the latest release without a problem.

**Comment by andrevmatos** [comment]
Thank you! I experienced this, and was pleased to find out this had already been perceived and addressed. Great work!
