### ISSUE TITLE
Unexpected behavior in S-expression langs like lisp, fenell, racket, scheme and etc

### ISSUE THREAD

**Issue by gnsfujiwara** [altermo/ultimate-autopair.nvim#47]
I realized that in these programming languages, something happens that is not supposed to happen.

What happens:
```
Before                    Input                After
-----------------------------------------------------------
(defun foo (x y z)|)      <CR>          (defun foo (x y z)
                                           |
                                           )
```

what should happen:

```
Before                    Input                After
-----------------------------------------------------------
(defun foo (x y z)|)      <CR>          (defun foo (x y z)
                                           |)
```

**Comment by altermo** [comment]
Already added: [ac05c82](https://github.com/altermo/ultimate-autopair.nvim/commit/ac05c8297e97643b14c43176eae97aa15d1d7b8e); if there is any problem about it not working, please let me know.

**Comment by gnsfujiwara** [comment]
Oh sorry, this only occurs in commonlisp when I have treesitter active, I don't know what it could be.

**Comment by altermo** [comment]
Fixed; the problem was that `LanguageTree:lang()` returns commonlisp, and that `nvim_get_option_value('lisp',{filetype='commonlisp'})` doesn't return true cause the filetype of commonlisp files is lisp and not commonlisp, and a filetype of commonlisp doesn't exsist.

**Comment by CFiggers** [comment]
I'm having this exact issue with a different lisp-type language, Janet. It only happens when treesitter is activated. Is there a general fix for this problem? Thanks so much.

**Comment by altermo** [comment]
It seems that vim doesn't detect Janet as lisp, so:
```lua
vim.api.nvim_create_autocmd('FileType', {
    pattern = 'janet',
    callback = function() vim.o.lisp = true end
})
```

**Comment by CFiggers** [comment]
Thank you!
