### ISSUE TITLE
breaks with vim-eunuch

### ISSUE THREAD

**Issue by WhoIsSethDaniel** [altermo/ultimate-autopair.nvim#52]
Minimal config (init.lua):
```
vim.cmd [[
packadd! ultimate-autopair.nvim
packadd! vim-eunuch
]]
require('ultimate-autopair').setup {}
```
start nvim with this config:
```
nvim -u init.lua
```
Enter insert mode, type &lt;cr&gt;. Nothing happens, no newline. You can go back to normal mode, type 'o' and then type &lt;cr&gt; again. Same result. 
This only happens with `vim-eunuch` loaded along with `ultimate-autopair`.
I haven't dived deeply into what is causing the problem but it must be somewhere [here](https://github.com/tpope/vim-eunuch/blob/67f3dd32b4dcd1c427085f42ff5f29c7adc645c6/plugin/eunuch.vim#L489-L506).

vim-eunuch is here: https://github.com/tpope/vim-eunuch
It's a tpope plugin so it's probably reasonably popular. Plus it has been around awhile.

**Comment by altermo** [comment]
Fixed; the problem was that vim-eunuch doesn't handle neovim-lua-callback keymaps.

**Comment by WhoIsSethDaniel** [comment]
Thanks for the quick turnaround.
