### ISSUE TITLE
Custom pairs

### ISSUE THREAD

**Issue by ribru17** [altermo/ultimate-autopair.nvim#53]
Is there a way for the user to add their own pairs in this plugin? E.g. I would like to be able to add a pair for markdown files of `$`, `$`, when the first `$` is not preceded by a backslash. Is this possible?

**Comment by altermo** [comment]
Yes, that is possible:
```lua
{
  {'$','$',ft={'markdown'},multiline=false},
}
```

**Comment by mawkler** [comment]
@altermo Where should I put this line? If I put it in `internal_pairs` all other pairs disappear:

```lua
require('ultimate-autopair').setup({
  internal_pairs = {
    { '$', '$', ft = { 'markdown' }, multiline = false },
  },
})
```

**Comment by altermo** [comment]
Put it straight into config:
```lua
require'ultimate-autopair'.setup({
  {'$','$',ft={'markdown'},multiline=false},
})
```

**Comment by mawkler** [comment]
@altermo Aha, thank that works!

I would like the ability to autopair both `*` and `**` in markdown. That is, when I type the first `*` I want this (`|` is the cursor):

```
*|*
```

And when I type the second `*` I want this:

```
**|**
```

Is this possible?

I tried this, but that didn't work:

```lua
require('ultimate-autopair').setup({
  { '*',  '*',  ft = { 'markdown' }, multiline = false },
  { '**', '**', ft = { 'markdown' }, multiline = false },
})
```

**Comment by altermo** [comment]
That feature is one of the things that is currently on the to-do list.
I will try to implement it, though it may take time.

**Comment by mawkler** [comment]
@altermo I see, thank you!

**Comment by altermo** [comment]
Implemented; now it should work.

**Comment by mawkler** [comment]
@altermo Seems to be working! Thank you very much for implementing it so quickly!
