### ISSUE TITLE
How to disable some feature for the specific filetype

### ISSUE THREAD

**Issue by XXiaoA** [altermo/ultimate-autopair.nvim#55]
What should I do to disable the autopair of `()` `{}` `[]` in a specific filetype, while other features working?

**Comment by altermo** [comment]
Use:
```lua
require'ultimate-autopair'.setup{
    config_internal_pairs={
        {'(',')',nft={filetype}},
        {'{','}',nft={filetype}},
        {'[',']',nft={filetype}},
    }
}
```

**Comment by XXiaoA** [comment]
Thanks for the fast reply and your awesome plugin!

**Comment by Ciel-MC** [comment]
What about disabling only a certain aspect? I want to disable surrounding just for Rust because r-a already provides it(and I find it more accurate).

P.S. simrat's rust-tools doesn't have it, I just finished it on my fork(which is why it only now became a problem)

**Comment by altermo** [comment]
If you only want to disable surrounding for one pair then:
```lua
require'ultimate-autopair'.setup{
    {'<','>',dosuround=function () return  vim.o.filetype~='rust' end},
    --Note: use `config_internal_pairs={...}` if your configuring an builtin pair
}
```
However, disable surround globally is not possible via function, so just pass two configs to the plugin:
```lua
local upair=require'ultimate-autopair'
local config=upair.extend_default{
    extensions={
        filetype={nft={'rust'}},
    },
    --your config
}
local other_config=vim.deepcopy(config)
other_config.extensions.filetype.nft=nil
other_config.extensions.filetype.ft={'rust'}
other_config.extensions.surround=false
upair.init({config,other_config})
```
