### ISSUE TITLE
multiline surrounds extra characters

### ISSUE THREAD

**Issue by pnwatin** [altermo/ultimate-autopair.nvim#56]
Hi, 
Love this plugin ! 
here is my `config_internal_pairs` :
```
    opts = {
      config_internal_pairs = { 
        { "{", "}", suround = true, multiline = true },
        { "[", "]", suround = true, multiline = true },
        { "(", ")", suround = true, multiline = true },
        { "'", "'", multiline = true },
      },
    },
```
when i surround on an existing pair on multine with following characters (like `{\n};` or `'\n'sad`) the new surrounding ends behind the first following character :
```
{(
// ...
);}
```
can i change this behavior ? thanks a lot 🙏

**Comment by altermo** [comment]
fixed
