### ISSUE TITLE
Causes NeoVim to get stuck with high CPU for Rust files 

### ISSUE THREAD

**Issue by weilbith** [altermo/ultimate-autopair.nvim#57]
Hey 👋🏾 

I really like the plugin and I'm happy with it so far. Just that I have to disable it for my Rust development. Because as soon as I type any pair character, it makes NeoVim hang completely. If I inspect my processes (just `htop`), I can see a `neovim` child with ~200% CPU which is just like `neovim --embed <rust_file>`. The only way to get again is to kill the process completely.

Most of the time, I see at least the matching character being inserted automatically. Sometimes not even that. 

Do you have an idea what the plugin is triggering after a match that could cause these issues? 
I don't know how to debug this except trying to disable and enable any kind of feature with try-and-error.

Would be amazing to use this plugin to full extend. Especially since I write a good bunch of Rust code. 🙈 
By now I disabled it for Rust files.

Thanks for any help!

**Comment by altermo** [comment]
I have multiple ideas of what could be happening.
Try the following things and report what makes neovim not freeze:

  **First, try disabling treesitter:**
```lua
require('ultimate-autopair').setup{
    extensions={tsnode=false}
}
```
  **Second, try disabling all extensions:**
```lua
require('ultimate-autopair').setup{
    extensions=false
}
```
  **Third, try disabling multiline:**
```lua
require('ultimate-autopair').setup{
    multiline=false
}
```

**Comment by weilbith** [comment]
Thanks for the quick reply. The `extensions=false` was preventing the freeze and made it work. So I guess I need to enable/disable each extension now to figure which it is. Give me a moment.

**Comment by weilbith** [comment]
Okay, so it is the `alpha` extension which causes the issue. if I add `extensions = { alpha = false }` it works fine.

**Comment by altermo** [comment]
There are multiple functions in `alpha` which may be the cause.
I suspect `vim.filetype.get_option` as that can be effected by user config outside of the plugin,
so try running `:lua=vim.filetype.get_option('rust','iskeyword')`

**Comment by weilbith** [comment]
Yep, you found it. I get the result printed, but then my NeoVim is frozen again.

**Comment by altermo** [comment]
Okay, created a new option for `alpha`: `no_ft_iskeyword` which uses buffer iskeyword instead of treesitter filetype iskeyword.
You can set it with:
```lua
require('ultimate-autopair').setup{
    extensions={alpha={no_ft_iskeyword=true}}
}
```

I would recommend making it so that `vim.filetype.get_option('rust',...)` doesn't freeze as other plugins may use it.

**Comment by weilbith** [comment]
Cool!

How would I use the configuration system to only set this new option for Rust files? 🤔

I must admit I don't understand the second part. 🙈

**Comment by altermo** [comment]
Almost all extension options can be set as functions:
```lua
require('ultimate-autopair').setup{
    extensions={alpha={no_ft_iskeyword=function(o)
        return 'rust'==require'ultimate-autopair.utils'.getsmartft(o)
    end}}
}
```

The second part is about how you should probably fix the problem that causes `vim.filetype.get_option('rust',...)` to crash as other plugins may use it.


Also, I quickly fixed a bug with the option. (so update)

**Comment by weilbith** [comment]
Alright, I'm using that option now. So I guess we can close this issue.

Thank you very much for your quick help! 🙏🏾
