### ISSUE TITLE
Inserts a semicolon(;) after if statement for C and C++ files

### ISSUE THREAD

**Issue by Rishabh672003** [altermo/ultimate-autopair.nvim#6]
https://user-images.githubusercontent.com/53911515/219728873-42f7f4a8-34e8-48bc-b11d-58254f69041f.mp4

I dont think this should be a default behavior as in most case you write an else if or an else statement after if

**Comment by Rishabh672003** [comment]
https://user-images.githubusercontent.com/53911515/219731851-59f69de5-2070-4b5a-ad98-5e06f877e1e0.mp4

also the same thing for do as while always comes after it

**Comment by Wa1tee** [comment]
Remove 'c' and 'cpp' from the list on the line `addsemi={'c','cpp','rust'},` and restart nvim

**Comment by Rishabh672003** [comment]
oh i guess i should have read the documentation my bad, also thank you
