### ISSUE TITLE
How to map keys myself?

### ISSUE THREAD

**Issue by weilbith** [altermo/ultimate-autopair.nvim#60]
Hey 👋🏾 

I must admit that I'm quite in favor of mapping keys in NeoVim myself and don't use plugin configurations to do so. Anyhow, I want this explicitly for the `<CR>` mapping, as this currently causes issues for me. Sometimes it just works, but most of the time it does no more. So I would like to try this myself. But I fail to.

I inspected the mapping the plugin sets itself and it points me to the function call `require('ultimate-auto.core').run_run('<CR>')`. But that gives me a `attempt to call nil value` error. From here I struggle to understand the code behind it.

Could you help me please? 🙏🏾 
Thank you very much!

PS:
Currently I get errors with `nvim-cmp` when I hit enter while completing which looks like below. Afterwards `nvim-cmp` is "crashed" and I have no auto-complete anymore. Despite the fact I can't select completions anymore.

```
...site/pack/packer/start/nvim-cmp/lua/cmp/utils/window.lua:201: E565: Not allowed to change text or change window
stack traceback:
        ...t/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:77: in function <...t/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:74>
        [C]: in function 'nvim_win_hide'
        ...site/pack/packer/start/nvim-cmp/lua/cmp/utils/window.lua:201: in function 'close'
        ...cker/start/nvim-cmp/lua/cmp/view/custom_entries_view.lua:233: in function 'close'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/view.lua:138: in function 'close'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/core.lua:370: in function 'confirm'
        ...re/nvim/site/pack/packer/start/nvim-cmp/lua/cmp/init.lua:222: in function 'confirm_selected_entry'
        ...nvim/pack/plugins/opt/ultimate-autopair/plugin/setup.lua:13: in function 'v'
        ...e-autopair.nvim/lua/ultimate-autopair/extension/cond.lua:81: in function 'cond'
        ...e-autopair.nvim/lua/ultimate-autopair/extension/cond.lua:97: in function <...e-autopair.nvim/lua/ultimate-autopair/extension/cond.lua:96>
        [C]: in function 'xpcall'
        ...t/ultimate-autopair.nvim/lua/ultimate-autopair/debug.lua:97: in function 'run'
        ...pt/ultimate-autopair.nvim/lua/ultimate-autopair/core.lua:96: in function <...pt/ultimate-autopair.nvim/lua/ultimate-autopair/core.lua:87>
(Ingore the line bellow) press y to start debugger (or c to copy traceback):
```

EDIT:
Very likely, the issue is on my configuration side. But I would like to be at least able to trigger the `<CR>` behavior myself programmatically. 😃

**Comment by altermo** [comment]
The thing is that each key gets past through `nvim_replace_termcodes`, so it is `\r` and not `<cr>`.
Note that `core.run` returns an action and requires the mapping to be an `<expr>`, activating textlock, which you probably don't want.
So I would guess you want this:
```lua
local core=require'ultimate-autopair.core'
vim.keymap.set('i','\r',function()
    vim.api.nvim_feedkeys(core.run_run('\r'),'n',false)
end)
```
(I'm currently working on the next version of the plugin where this will be simplified)

**Comment by weilbith** [comment]
Nice, thank you!

How can I know disable the automatic mapping by the plugin? I have some issues with the loading order, so my mappings gets overwritten by the one of the plugin atm. But if I set in the plugin config the `cr = { map = '' }`, then the  `run_run` function does not work anymore. Can I disable the plugin to create the mapping, but still have the function working?

> (I'm currently working on the next version of the plugin where this will be simplified)

Cool! :+1:

**Comment by altermo** [comment]
It is not possible (yet).
But you could do `cr = { map = '<plug>ultimate-autopair-CR' }` and then use
```lua
local core=require'ultimate-autopair.core'
vim.keymap.set('i','\r',function()
    vim.api.nvim_feedkeys(core.run_run(vim.api.nvim_replace_termcodes('<plug>ultimate-autopair-CR',true,true,true)),'n',false)
end)
```

**Comment by weilbith** [comment]
Nice, that does the job. Good idea! 👍🏾 
Thank you very much for your help!

**Comment by weilbith** [comment]
Damn. I get sometimes recursive mapping errors now. Don't know where they are coming from. 😑 
It triggers when I hit enter and there is nothing happening by autopair. So if I type `(<CR>`, that is fine. But if I just type `<CR>` anywhere else to create a new line, it fails with the recursion error. 🤔 
Surprised that also explicitly setting `noremap = true` doesn't help. 😖

**Comment by altermo** [comment]
Oh, I forgot that `run_run` returns the inputted key, so:
```lua
local core=require'ultimate-autopair.core'
vim.keymap.set('i','\r',function()
    local key=core.run_run(vim.api.nvim_replace_termcodes('<plug>ultimate-autopair-CR',true,true,true))
    if key==vim.api.nvim_replace_termcodes('<plug>ultimate-autopair-CR',true,true,true) then
        vim.api.nvim_feedkeys('\r','n',false)
    else
        vim.api.nvim_feedkeys(key,'n',false)
    end
end)
```

**Comment by weilbith** [comment]
Alright, this finally works now. 👌🏾 
Despite that part: I love how powerful this plugin is. 😊
