### ISSUE TITLE
Automatic newline and indentation for template literals in JavaScript

### ISSUE THREAD

**Issue by marlun** [altermo/ultimate-autopair.nvim#61]
This might be connected to #59 or at least similar. I'm not sure if this is something that this plugin should do or not. When writing for example a web component in JavaScript I might start with:

```javascript
class MyComponent extends HTMLElement {|}
```

Pressing `CR` will now give me 

```javascript
class MyComponent extends HTMLElement {
  |
}
```

Then I continue writing

```javascript
class MyComponent extends HTMLElement {
  render() {
    this.innerHTML = `|`
  }
}
```

Now when I press `CR` it gives me

```javascript
class MyComponent extends HTMLElement {
  render() {
    this.innerHTML = `
    |`
  }
}
```

Would it possible to have the same logic here as with `{}`? I'm not sure if it's all ultimate-autopair doing the "extra newline and indentation" or if it's a combination of ultimate-autopair and Treesitter indentation but it feels so smooth and nice with `{}`.

**Comment by altermo** [comment]
Yes:
```lua
require('ultimate-autopair').setup{
  config_internal_pairs={
    {'`','`',newline=true}
  }
}
```

**Comment by marlun** [comment]
With that

```javascript
class MyComponent extends HTMLElement {
  render() {
    this.innerHTML = `|`;
  }
}
```

still results in

```javascript
class MyComponent extends HTMLElement {
  render() {
    this.innerHTML = `
    |`;
  }
}
```

However 

```javascript
class MyComponent extends HTMLElement {
  render() {
    const test = `|`;
  }
}
```

results in 

```javascript
class MyComponent extends HTMLElement {
  render() {
  const test = `
|
  `
  }
}
```

I'm guessing that last one with the caret on the first column has to do with the treesitter indentation because if I try to format the code it stays in the first column instead of being indented as I expect.

Also, with tagged template literals sometimes you will write

```javascript
return html`|`
```

That will result in

```javascript
class MyComponent extends HTMLElement {
  render() {
    const test = html`
    |`;
  }
}
```

**Comment by altermo** [comment]
It's treesitter, specifically that the plugin isolates text inside injected blocks of code.
So if you don't care about this feature (or string isolation) then disable the extension:
```lua
require('ultimate-autopair').setup{
  config_internal_pairs={
    {'`','`',newline=true}
  },
  extensions={
    tsnode=false
  },
}
```

**Comment by marlun** [comment]
> It's treesitter, specifically that the plugin isolates text inside injected blocks of code.
So if you don't care about this feature (or string isolation) then disable the extension:

I'm not sure what the isolation part means?

Disabling tsnode I do get the cursor on its own line but the cursor is left on the first column of the line instead of one extra indentation like with `{|}`. Should I look into TS indentation to fix that?

**Comment by altermo** [comment]
When I mean isolated, I mean that the multi line open pair detection and all other detection will only be done in a region/outside a region.

And for the indentation, yes (as this plugin uses whatever indentation system neovim is set up with).

**Comment by marlun** [comment]
I don't really understand the region part but I'll keep it like this for now and continue researching why the indentation is not the way I want with Treesitter. I'll close the issue, thanks for the help!
