### ISSUE TITLE
Bug: Autopair doesn't respect comments or strings in d language

### ISSUE THREAD

**Issue by nxuv** [altermo/ultimate-autopair.nvim#62]
ultimate-autopair version: v0.6
nvim version: v0.9.4
luajit version: 2.1.1696795921

How it's supposed to work:
![autopair_in_c](https://github.com/altermo/ultimate-autopair.nvim/assets/60989682/51959f24-0b96-4083-b7ed-efb575707025)

How it works:
![autopair_onemore](https://github.com/altermo/ultimate-autopair.nvim/assets/60989682/c70f92cb-5934-4344-8d52-d950554edb2b)

I've tested a bit and narrowed it down:
```d
// foreach (string l; layers) { // <- !!this brakes it!!
for (int i = 0; i < layers.length; ++i) {
}
```

If to have any code with unclosed pair it'll try to close it even if it shouldn't.

Tested it with other types of pairs and it breaks it for each of cases:
```d
// ({["'
// This upper line will completely break autopair
```
Even more, autopair does respect `\'`, but:
```d
"'";
// Upperline breaks ' pairs
'"';
// And this one breaks " pairs
```

Same goes the other way
```d
// }
// Upper line breaks { pair
```

And so it does for all of them.

**Comment by altermo** [comment]
First, do you have treesitter enabled?
If yes then pleas tell me the type of the nodes, as each treesitter language has its own name of a string/comment nodes type, and I will add them to the list of special tsnodes.

**Comment by nxuv** [comment]
Yes I do and how do I get those nodes?

**Comment by altermo** [comment]
use `:InspectTree` and hover over the object, then in the tree view, copy the highlighted name.
Note to get the whole string tsnode type instead of just the string content tsnode type.

**Comment by nxuv** [comment]
Not sure what you mean by whole string tsnode, but

"string"
```
     (exp_initializer) ; [4:12 - 19]
      (primary_expression) ; [4:12 - 19]
       (string_literals) ; [4:12 - 19]
        (double_quoted_string) ; [4:12 - 19]
```

'c' (char)
```
     (exp_initializer) ; [5:10 - 12]
      (primary_expression) ; [5:10 - 12]
       (character_literal) ; [5:10 - 12]
```

r"wysiwyg"
```
     (exp_initializer) ; [7:12 - 20]
      (primary_expression) ; [7:12 - 20]
       (string_literals) ; [7:12 - 20]
        (wysiwyg_string) ; [7:12 - 20]
```

\`wysiwyg_alt\`
```
     (exp_initializer) ; [6:12 - 17]
      (primary_expression) ; [6:12 - 17]
       (string_literals) ; [6:12 - 17]
        (alternate_wysiwyg_string) ; [6:12 - 17]
```

// comment
```
(line_comment) ; [1:1 - 2:0]
```

/* block comment */
```
(block_comment) ; [2:1 - 11]
```

/+ nested comment +/
```
(nesting_block_comment) ; [3:1 - 12]
```

This should be all of them I guess...
Language is `d`
Treesitter-D repo: https://github.com/CyberShadow/tree-sitter-d

**Comment by altermo** [comment]
Okay, added the tsnode types.
If everything works correctly, close the issue.

**Comment by nxuv** [comment]
It did not work, everything is still as it was

Here's screenshot with InspectTree (had to properly init variables or it wouldn't parse correctly)

![image](https://github.com/altermo/ultimate-autopair.nvim/assets/60989682/b4691ee9-1e23-4f97-a04b-4ce65984f080)

**Comment by altermo** [comment]
Which parts don't work?

**Comment by nxuv** [comment]
None of them did

**Comment by altermo** [comment]
Hmm...
Try completely reinstalling the plugin (remove from plugin list, clean plugins, and add back), as there is something wrong with the repository which makes it sometimes not update.
If that doesn't work then the only option is you creating a minimal reproducible config/script. (as it works on my side (tested on neovim v9.1))

**Comment by nxuv** [comment]
![autopair_epic_fail](https://github.com/altermo/ultimate-autopair.nvim/assets/60989682/02d9cd60-a114-4b61-892d-f29e4bf77281)
Attaching gif as proof

Minimal config:
```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
    {
        "altermo/ultimate-autopair.nvim",
        event = {"InsertEnter", "CmdlineEnter"},
        branch = "v0.6", -- TODO: check later
        config = function() require("ultimate-autopair").setup({}) end
    },
    {
        'nvim-treesitter/nvim-treesitter',
        config = function() require("nvim-treesitter").setup({}) end
    }
})
```

Steps to reproduce:
- Open nvim
- `:e test.d`
- Type:
```d
// {
{
```
- Press } twice

**Comment by altermo** [comment]
You forgot to install the `d` treesitter module. (Just add `build=":TSInstallSync d"`)

Also there's something about the `comment` treesitter module.
It breaks autopairing _only_ on the first char on the next line of the comment.
i.e.
```d
// {
{ //<-- this character
{ //<-- but not this one
```
The reasoning behind this behavior is that most languages treesitter comments don't extend to the end (next line), so I made it so that they are extended one character further, but `d`'s treesitter comment nodes extend to the next line, so it detects that the first character next line as a comment. Or I think this is what's causing it, but I haven't checked.

**Comment by nxuv** [comment]
I did installer treesitter module, otherwise InspectTree wouldn't work

Also you can clearly see in gif that I've stepped past "next line" and also strings weren't working either

**Comment by altermo** [comment]
Wow, sorry for that, the thing that makes it not work is using `<enter>` instead of (what I use) `<esc>o` (or `<A-o>`) when creating new lines.

I'll look into it, whether it is a bug in the plugin or a bug in something else, but that might take some time as I don't even know where to start.

**Comment by altermo** [comment]
Or not

**Comment by altermo** [comment]
Okay, I can't really make sense of it, depending on if some of the code was already in the file, whether you started the insertion of the comment part with `O` instead of `i`/`a`/`o`, and what kind of newline creator (`<enter>` or `<esc>o`) was used (note that `<enter><esc>ddo`==`<enter>` for some reason), it may or may not work.

**Comment by nxuv** [comment]
That's super wierd

**Comment by altermo** [comment]
I found the issue... Where should I even begin:
1. The plugin create the key bindings `<cr>`, `<space>`, `}`, `{` and more.
2. Whenever the plugin processes a key, `vim.treesitter.get_node` and `vim.treesitter.get_parser` gets run.
3. If `vim.treesitter.get_node` or `vim.treesitter.get_parser` gets called near

**Comment by altermo** [comment]
I found the issue... Where should I even begin?
## The happenings
1. The plugin creates some keybindings (including `<space>`, `<cr>`, `{` and `}`)
2. When the plugin processes a key, `vim.treesitter.get_parser` gets called 
3. When `vim.treesitter.get_parser` gets called when the cursor is near a comment, including the first char in the line after the comment, the `d` parser soft locks and processes everything after that as part of the comment (not exactly).
    + This doesn't happen after `vim.treesitter.start` gets called after the buffer is loaded (or something like that)
## The temporary solution
Call `vim.treesitter.start` after the buffer is loaded with this:
```lua
vim.api.nvim_create_autocmd('FileType',{pattern='d',callback=function()
    vim.treesitter.start()
end})
```
<details><summary>minimal config with fix</summary>

```lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)

require('lazy').setup({
    {
        "altermo/ultimate-autopair.nvim",
        event = {"InsertEnter", "CmdlineEnter"},
        branch = "v0.6", -- TODO: check later
        config = function() require("ultimate-autopair").setup({}) end
    },
    {
        'nvim-treesitter/nvim-treesitter',
        config = function() require("nvim-treesitter").setup({}) end
    }
})
vim.api.nvim_create_autocmd('FileType',{pattern='d',callback=function()
    pcall(vim.treesitter.start)
end})
```
</details>

## Further actions
I'll formulate a bug report about this to either neovim or the d-treesitter-parser if it isn't already present.

**Comment by altermo** [comment]
Okay, it is a problem with the `d` parser.

**Comment by altermo** [comment]
Okay, possibly fixed it. ([6fd0d6a](https://github.com/altermo/ultimate-autopair.nvim/commit/6fd0d6aa976a97dd6f1bed4d46be1b437613a52f))

**Comment by nxuv** [comment]
Dunno if it fixed original server, but I've switched my D lsp to https://github.com/gdamore/tree-sitter-d and it works like a charm (and autopair is now fine)

Server that nvim-treesitter provides by default is super crappy and honestly I have no idea why they haven't switched it yet

Also even with 6fd0d6a autopair is blazingly faster then most alternatives I've tried
