### ISSUE TITLE
Strange behaviour for > brackets

### ISSUE THREAD

**Issue by kaiphat** [altermo/ultimate-autopair.nvim#64]
I wanted to add `<>` brackets support, so i changed my config:
```lua
return {
	'altermo/ultimate-autopair.nvim',
	branch = 'v0.6',
	event = { 'InsertEnter' },
	config = function()
		local p = require 'ultimate-autopair'

		p.setup {
			close = {
				multi = true,
			},
			extensions = {
				suround = {
					p = 100,
				},
			},
			internal_pairs = {
				{ '[', ']', fly = true, dosuround = true, newline = true, space = true },
				{ '(', ')', fly = true, dosuround = true, newline = true, space = true },
				{ '{', '}', fly = true, dosuround = true, newline = true, space = true },
				{ '<', '>', fly = true, dosuround = true, newline = true, space = true },
				{ '"', '"', suround = true, multiline = false, alpha = { 'txt' } },
				{
					'\'',
					'\'',
					suround = true,
					cond = function(fn) return not fn.in_lisp() or fn.in_string() end,
					alpha = true,
					nft = { 'tex', 'latex' },
					multiline = false,
				},
				{ '`', '`', nft = { 'tex', 'latex' }, multiline = false },
				{ '``', '\'\'', ft = { 'tex', 'latex' } },
				{ '```', '```', newline = true, ft = { 'markdown' } },
				{ '<!--', '-->', ft = { 'markdown', 'html' } },
				{ '"""', '"""', newline = true, ft = { 'python' } },
				{ '\'\'\'', '\'\'\'', newline = true, ft = { 'python' } },
			},
		}
	end,
}

```

It's working in lua. But not working in typescript files.

**Comment by altermo** [comment]
Can you give a minimal config?
I suspect that it has something to do with tree-sitter-injected languages. (the plugin uses those to only do open pair detection in only that region)

**Comment by kaiphat** [comment]
My config: https://github.com/kaiphat/dotfiles/tree/master/nvim
I'm going to try without plugins

**Comment by kaiphat** [comment]
Yes, all work with your plugin only. How it fix...
Actually, it works in simple typescript file. But not working in file with ~350 loc.

**Comment by altermo** [comment]
The second idea, maybe it's multiline open pair detection, try setting `multiline = false`
Check if the file contains any `<` or `>` which might cause an issue.

**Comment by kaiphat** [comment]
No, it didn't affect

**Comment by kaiphat** [comment]
Yes, it works) but i want multiline so much:)

**Comment by kaiphat** [comment]
> Check if the file contains any < or > which might cause an issue.

File contains `<>`.

**Comment by kaiphat** [comment]
I have similar problem with big files ~2000 loc.

<img width="270" alt="image" src="https://github.com/altermo/ultimate-autopair.nvim/assets/53742299/6d54e10e-488b-436e-bc6e-a07854793d6b">

When i type `)`

<img width="270" alt="image" src="https://github.com/altermo/ultimate-autopair.nvim/assets/53742299/9daa5913-c9b4-4cbe-837d-eae114750167">

I got extra `)`.
But it happens only in big files.

**Comment by altermo** [comment]
The second problem of big files breaking multiline auto-pairing is the way I currently have a maximum line size limit.
I'm planning to remove it once I do some more optimizations in the plugin, but until then you can disable this feature with
```lua
require'ultimate-autopair.utils'.maxlines=math.huge
```

For the first problem of wanting multiline to work for `<>` in typescript, my best solution is to disable the pair detection in the nodes which may cause problems, (like `a>b` or `(a)=>a*a`). It is not the best solution, but I can't do better without some complicated tree-sitter querying.
(Also, you don't need to modify `internal_pairs`, if you want to configure internal pairs, use `config_internal_pairs`)
```lua
p.setup{
    {'<','>',fly=true,dosuround=true,newline=true,space=true,cond=function (fn)
        return not fn.in_node{'arrow_function','binary_expression','augmented_assignment_expression'}
    end},
}
```

**Comment by kaiphat** [comment]
Wow, thank you so much:) It works.
But... if i add `<>` to config_internal_pairs i get error, because this there aren't this pairs in `internal_pairs`

**Comment by altermo** [comment]
Yeah, I should make better documentation.
`config_internal_pairs` is used to set options for pairs in `internal_pairs` so that one doesn't need to repeat the content of `internal_pairs` in their config to modify a single option for one of the pairs in `internal_pairs`. `internal_pairs` should not be changed by configuration and I'm planning (in the next major release) to rename it to `__internal_pairs` to signal that this should not be changed, and also add a short comment about where to look in the documentation to add your pairs.

**Comment by kaiphat** [comment]
I about this one.
<img width="1728" alt="image" src="https://github.com/altermo/ultimate-autopair.nvim/assets/53742299/445a68af-569b-41fe-a51c-5bcc9fab31ee">

**Comment by altermo** [comment]
I only added `config_internal_pairs` to do some clarification about something else, but it's not important for this problem.
Basically don't use `config_internal_pairs` to solve this problem.

**Comment by kaiphat** [comment]
Ok, thank you)
