### ISSUE TITLE
Fly mode conflict with treesitter

### ISSUE THREAD

**Issue by marlun** [altermo/ultimate-autopair.nvim#65]
I have the following config that you've provided me with:

```lua
	{
		'altermo/ultimate-autopair.nvim',
		event = { 'InsertEnter', 'CmdlineEnter' },
		branch = 'v0.6',
		config = function()
			require('ultimate-autopair').setup({
				extensions = { fly = { nofilter = true } },
				config_internal_pairs = {
					{ '"', '"', fly = true },
					{ "'", "'", fly = true },
					{ "`", "`", newline = true },
				},
			})
		end,
	},
```

I'm trying this by putting the caret at `|` here: `require('ultimate-autopair|').setup({` and pressing `)`. If I have nvim-treesitter enabled, even if the nvim-treesitter config is an empty object it just enters a `)` however if I remove nvim-treesitter the caret jumps to `require('ultimate-autopair')|.setup({`

**Comment by altermo** [comment]
Should be fixed

**Comment by marlun** [comment]
Yes, it seems to work now, thanks! ❤️
