### ISSUE TITLE
[Question] How to ignore a specific parser?

### ISSUE THREAD

**Issue by alexmozaidze** [altermo/ultimate-autopair.nvim#69]
# Question

How do I specify to ultimate-autopair which parsers it should ignore?

I want to make ultimate-autopair ignore [tree-sitter-comment] since it's an "embedded parser" of some sort, which messes with my custom queries when making [tree-sitter-comment] work in HTML. (See [tree-sitter/tree-sitter-html #73](https://github.com/tree-sitter/tree-sitter-html/issues/73))

# Problem

If in HTML I do the following (where `|` is the cursor):
```html
<!--|
```
It works as expected:
```html
<!--|-->
```
But pressing `<space>` doesn't work as expected, since it's now inside the comment parser:
```html
<!-- |-->
```

This is an issue to be fixed in the HTML parser, but it would be nice to have a temporary solution to ignore the comment parser, avoiding the problem entirely.

[tree-sitter-comment]: https://github.com/stsewd/tree-sitter-comment

**Comment by altermo** [comment]
Space isn't by default enabled for HTML comment pair, so add this to config:
```lua
setup({
    config_internal_pairs={
        {'<!--','-->',space=true},
    },
})
```
As for the feature, I'm planning to implement it in the next release, as it requires a complete overhaul of how the treesitter system works.

**Comment by altermo** [comment]
Currently not possible, as the way the current implementation works is by using get_node, and there are no easy ways to make get_node ignore some injected parser.
In the next release, I plan to change it so that instead of using get_node, it will use treesitter-queries to get nodes and injected-langs, which will make this feature possible.
