### ISSUE TITLE
Issue in Markdown files and VimWiki

### ISSUE THREAD

**Issue by feekApp** [altermo/ultimate-autopair.nvim#7]
When using a markdown file and [VimWiki](https://github.com/vimwiki/vimwiki) some errors occurs.

How to reproduce:

- Create a new Markdown file `nvim test.md'
- add header + space `# `
- stay in insert mode
- press backspace

```
E5108: Error executing lua: ...-autopair.nvim/lua/ultimate-autopair/utils/info_line.lua:140: attempt to index local 'node' (a nil value)
stack traceback:
        ...-autopair.nvim/lua/ultimate-autopair/utils/info_line.lua:140: in function 'filter_string'
        ...ultimate-autopair.nvim/lua/ultimate-autopair/maps/bs.lua:121: in function <...ultimate-autopair.nvim/lua/ultimate-autopair/maps/bs.lua:115>
```

**Comment by altermo** [comment]
Should be fixed. If not then please let me know, otherwise close this issue.

**Comment by feekApp** [comment]
Thnx for the quick fix, seems to work!
