### ISSUE TITLE
Builtin C-style block comment support

### ISSUE THREAD

**Issue by Bekaboo** [altermo/ultimate-autopair.nvim#70]
Hi, firstly thank you for making this plugin. It works better than any other existing solutions and acts exactly in a way I would expected, especially in situations where we have an unmatched pair on a different line or inserting single quotes in double-quoted strings, etc. All the edge cases I met with other autopair plugins are handled perfectly in this one. Congrats!

It would be even better if we can have builtin C-style block comment support, i.e.

```
/| --> type '*' --> /*|*/ --> type space --> /* | */
--> hit <CR>
-->
/*
 * |
 */
```

Currently using this simple setup:

```lua
require('ultimate-autopair').setup(
  {
    {
      '/*',
      '*/',
      ft = { 'c', 'cpp', 'cuda' },
      multiline = true,
      newline = true,
      space = true,
    },
  }
)
```

I can get most things right, except that after hitting `<CR>` I get this:

```
/*
 *
 * */
```

not this:

```
/*
 *
 */
```

It would be great if ultimate-pairs can provide out-of-the-box support for this, or is there an easy way to achieve the same effect using the setup function? Thanks in advance!

**Comment by altermo** [comment]
I mean it only is two lines of code to implement, so.. https://github.com/altermo/ultimate-autopair.nvim/commit/2338e282986017094ef9399a3d07a9b908c5bd3f
If it works for you, close the issue.

**Comment by Bekaboo** [comment]
Thanks! Problem solved.
