### ISSUE TITLE
[Question] - JSX Support

### ISSUE THREAD

**Issue by sorrowfulfloyd** [altermo/ultimate-autopair.nvim#71]
Hi all.

I'm new to Neovim and don't know much about configuring plugins, installed this plugin to save myself sometime closing pairs in JSX,
but as it works in HTML or else, I couldn't get it to work with JSX. Is it a missing feature, or do I have to configure something?

Thanks in advance, nice plugin.

**Comment by altermo** [comment]
Can you describe what exactly isn't working?

**Comment by sorrowfulfloyd** [comment]
When I type any HTML element in a JS function (that's what JSX is) it doesn't autopair like in HTML.
It's just HTML tags inside JS essentially.

**Comment by altermo** [comment]
This plugin doesn't yet support auto-pairing HTML elements...
If you want that feature, check out [nvim-ts-autotag](https://github.com/windwp/nvim-ts-autotag) (requires [treesitter](https://github.com/nvim-treesitter/nvim-treesitter))
Here is a minimal config for how to set up the plugin:
```lua
for _,url in ipairs{
  'windwp/nvim-ts-autotag',
  'nvim-treesitter/nvim-treesitter'
} do
  local install_path=vim.fn.fnamemodify(url:gsub('.*/',''),':p')
  if vim.fn.isdirectory(install_path)==0 then
    vim.fn.system{'git','clone','https://github.com/'..url,install_path}
  end
  vim.opt.runtimepath:append(install_path)
end
require'nvim-treesitter.configs'.setup{
  ensure_installed={'javascript','html'},
  autotag={enable=true},
}
```

**Comment by sorrowfulfloyd** [comment]
aight, thanks for the help
