### ISSUE TITLE
alpha extension unexpected behavior

### ISSUE THREAD

**Issue by Bekaboo** [altermo/ultimate-autopair.nvim#72]
Config:

```lua
require('ultimate-autopair').setup({
  extensions = {
    alpha = { after = true },
  }
})
```

Repro
1. Setup ultimate-autopairs with the config above
2. Open a lua file, type the following:
    ```lua
    local foo = { bar, baz }
    ```
3. Move cursor back on the comma `F,`
4. `i(` to insert a pair after "bar"
5. The opening pair does not get completed while it should, "," should not be alpha.

**Comment by altermo** [comment]
Fixed. (https://github.com/altermo/ultimate-autopair.nvim/commit/8e1fcc8b7a29504d02ead3da62af9eccfc276f68)

**Comment by Bekaboo** [comment]
Thanks!
