### ISSUE TITLE
[Bug] Incorrect pair exiting behavior

### ISSUE THREAD

**Issue by TroySigX** [altermo/ultimate-autopair.nvim#75]
I have this rust code:
```rust
fn main() {
  let mut x = String::new();
  x.push_str(&format!("{}", 1));
}
```

After the last line in main, whenever I try to exit the parenthesis pair, `ultimate` incorrectly adds an extra closing paren.
For example: when exiting `Vec::new()`, instead of keeping the paren pair intact, `ultimate` results in this `Vec::new())`

**Comment by altermo** [comment]
Fixed (https://github.com/altermo/ultimate-autopair.nvim/commit/25c13e0ce167db0255456cac10158b27d2be30c0)
