### ISSUE TITLE
Request: option to disable autopair in command line

### ISSUE THREAD

**Issue by feekApp** [altermo/ultimate-autopair.nvim#8]
Hi,

Love your plugin!

I've a request. Currently the autopair is also active in the command line. Would be nice to be able to disable the actions into the command line.

== Feek

**Comment by altermo** [comment]
```lua
require'ultimate-autopair'.setup({cmap=false})
```

**Comment by feekApp** [comment]
Thnx, was not aware of this setting, but really thnx!
