### ISSUE TITLE
Way to prevent autocomplete if Esc is pressed?

### ISSUE THREAD

**Issue by sainttttt** [altermo/ultimate-autopair.nvim#80]
Hi! I'd like it so that if I press Esc (leaving insert mode) without entering another subsequent character, the autocomplete won't trigger. So for example just entering `(<Esc>` would end up with `(` or `('<Esc>` would give me `('`, but entering `('h<Esc>` would give me `('h')`. Would this be possible at all? I sort of have this functionality with some basic vim mappings as follows: 
```
imap [<esc> <c-v>[<esc>
imap ['<esc> <c-v>[<c-v>'<esc>
imap ["<esc> <c-v>[<c-v>"<esc>
imap ']<esc> <c-v>'<c-v>]<esc>
imap "]<esc> <c-v>"<c-v>]<esc>

imap {<esc> <c-v>{<esc>
imap {'<esc> <c-v>{<c-v>'<esc>
imap {"<esc> <c-v>{<c-v>"<esc>
imap '}<esc> <c-v>'<c-v>}<esc>
imap "}<esc> <c-v>"<c-v>}<esc>

imap (<esc> <c-v>(<esc>
imap ('<esc> <c-v>(<c-v>'<esc>
imap ("<esc> <c-v>(<c-v>"<esc>
imap ')<esc> <c-v>'<c-v>)<esc>
imap ")<esc> <c-v>"<c-v>)<esc>

imap '<esc> <c-v>'<esc>
imap "<esc> <c-v>"<esc>

imap "" <c-v>"<c-v>"
```
But the main issue being is that for multiple char imappings, it doesn't show all the characters on the screen as you type, but just one at a time, which is a bit jarring. Any help would be appreciated.

Thanks!

**Comment by altermo** [comment]
Hmm, let's see...
In the next version, I'm planning to add a command to reverse the previous action, so adding this feature wouldn't be hard. The problem is, that the next version release is a few months away... Anyway, here is some code I quickly cobbled up to do this:
```lua
local pair={
    --long pairs should be first
    {"('","')"},
    {"['","']"},
    {"{'","'}"},
    {'(',')'},
    {'[',']'},
    {'{','}'},
    {"'","'"},
    {'"','"'},
}
local ringbuf=''
vim.api.nvim_create_autocmd('InsertCharPre',{callback=function ()
    ringbuf=ringbuf:sub(-10)..vim.v.char
end})
vim.keymap.set('i','<esc>',function ()
    local line=vim.fn.getline'.'
    local col=vim.fn.col'.'
    local text_before_cursor=line:sub(1,col-1)
    local text_after_cursor=line:sub(col)
    for _,v in ipairs(pair) do
        local input=v.input
        if not input then
            input=''
            for i=1,#v[1] do
                input=input..v[1]:sub(i,i)..v[2]:sub(-i,-i)
            end
            v.input=input
        end
        if ringbuf:sub(-#input,-1)==input and
            text_before_cursor:sub(-#v[1],-1)==v[1] and
            text_after_cursor:sub(1,#v[2])==v[2]
        then
            return ('<del>'):rep(#v[2])..'<esc>'
        end
    end
    return '<esc>'
end,{expr=true})
```

**Comment by sainttttt** [comment]
Thanks for the reply! So I think this doesn't work 100% from my testing but the main thing is I was wondering if the autocomplete could not be triggered until I type another character. I think with this scheme it autocompletes and then if <Esc> is pressed it will clear out the autocomplete. Is that functionality possible at all currently? Thanks!

**Comment by altermo** [comment]
To trigger only after char insert, this is what I came up with:
```lua
local pair=[[([{"']]
local end_pair=[[)]}"']]
local pair_insert
local save={}
local group=vim.api.nvim_create_augroup('test',{})
vim.api.nvim_create_autocmd('InsertCharPre',{callback=function ()
    pair_insert=false
    for c in pair:gmatch'.' do
        if vim.v.char==c then
            local action=require'ultimate-autopair.core'.run(c)
            if action=='\aU\x80kr'--[[this is dont-new-undo + <right>]] then
                vim.api.nvim_feedkeys(action,'n',false)
                vim.v.char=''
                save={}
                return
            elseif #action>2 then
                table.insert(save,action:sub(3))
                pair_insert=true
                return
            end
        end
    end
    if not save[1] then return end
    local nsave=save
    save={}
    if end_pair:find(vim.v.char,1,true) then return end
    vim.api.nvim_feedkeys(table.concat(nsave),'n',false)
end,group=group})
vim.api.nvim_create_autocmd('CursorMovedI',{callback=function ()
    if pair_insert then return end
    save={}
end,group=group})
vim.api.nvim_create_autocmd('ModeChanged',{callback=function () save={} end,group=group})
for c in pair:gmatch'.' do
    vim.keymap.del('i',c)
end
```

**Comment by sainttttt** [comment]
Thanks so much for the replies! Unfortunately when I include that code, I don't see any change in the functionality. Am I missing something perhaps?

**Comment by altermo** [comment]
Don't use the older code snippet. Only use the newest one.

**Comment by sainttttt** [comment]
Yup I'm only using the newest code snippet

**Comment by altermo** [comment]
So it doesn't do this `|` +> `(` => `(|` +> `a` => `(a|)` (only trigger after another character is typed)
But instead this `|` +> `(` => `(|)` (trigger before another character is typed)
(`+>` is input, `=>` is result)

**Comment by sainttttt** [comment]
Isn't the second functionality just the default functionality for the plugin in general? And yeah the first one is the behavior that I'm looking for.

**Comment by altermo** [comment]
For me, the code snippet worked as the second functionality.

Here is the minimal demo I could use to create:

Open neovim with `nvim --clean` and run demo file with `:source`. It is a demo so it should install and run everything by itself. (freezes neovim while clean installing the plugin)

(also NOTE that I replaced `vim.keymap.set` with `vim.keymap.del` because they do the same thing.)

The demo file:
```lua
for _,url in ipairs{'altermo/ultimate-autopair.nvim','nvim-treesitter/nvim-treesitter'} do
    local install_path=vim.fn.fnamemodify(url:gsub('.*/',''),':p')
    if vim.fn.isdirectory(install_path)==0 then
        vim.fn.system{'git','clone','https://github.com/'..url,install_path}
    end
    vim.opt.runtimepath:append(install_path)
end
require'nvim-treesitter.configs'.setup{}
require('ultimate-autopair').setup{}
local pair=[[([{"']]
local end_pair=[[)]}"']]
local pair_insert
local save={}
local group=vim.api.nvim_create_augroup('test',{})
vim.api.nvim_create_autocmd('InsertCharPre',{callback=function ()
    pair_insert=false
    for c in pair:gmatch'.' do
        if vim.v.char==c then
            local action=require'ultimate-autopair.core'.run(c)
            if action=='\aU\x80kr'--[[this is dont-new-undo + <right>]] then
                vim.api.nvim_feedkeys(action,'n',false)
                vim.v.char=''
                save={}
                return
            elseif #action>2 then
                table.insert(save,action:sub(3))
                pair_insert=true
                return
            end
        end
    end
    if not save[1] then return end
    local nsave=save
    save={}
    if end_pair:find(vim.v.char,1,true) then return end
    vim.api.nvim_feedkeys(table.concat(nsave),'n',false)
end,group=group})
vim.api.nvim_create_autocmd('CursorMovedI',{callback=function ()
    if pair_insert then return end
    save={}
end,group=group})
vim.api.nvim_create_autocmd('ModeChanged',{callback=function () save={} end,group=group})
for c in pair:gmatch'.' do
    vim.keymap.del('i',c)
end
vim.cmd.split()
vim.cmd.enew()
vim.bo.buftype='nofile'
vim.api.nvim_input('i')
local function step(c)
    if #c==0 then return end
    vim.defer_fn(function ()
        if vim.fn.mode()~='i' then return end
        vim.api.nvim_input(c:sub(1,1))
        step(c:sub(2))
    end,1000)
end
step('(a)\n("a")\n(((a')
```

**Comment by sainttttt** [comment]
Okay it works now! I think it was how I was running the code before with my plugin manager and lazy loading. However I do have the issue that if I type `foo()` I end up with `foo())`. It seems to work fine for quotes though

**Comment by altermo** [comment]
I tried your neovim config...
Replace `local end_pair=[[)]}"']]` with `local end_pair=[[)]}"']]..'\29'`.

When neovim v0.10 is out, this will not be needed as A FEW MONTHS AGO I FIXED THE BUG CAUSING THIS ISSUE IN VIM (which I then [patched into neovim v0.10](https://github.com/neovim/neovim/pull/27049)).

**Comment by sainttttt** [comment]
It works now, thank you so much! And that's great to know that you fixed this bug in neovim v0.10 - will I have to revert the change back to `local end_pair=[[)]}"']] ` when 0.10 comes out? Either way thank you very much!

**Comment by altermo** [comment]
It's not necessary to revert when neovim 0.10 comes out.

**Comment by sainttttt** [comment]
So this overall has been working great but I've noticed there is a bug, where if I type a character that is supposed to autoclose but then delete it and then start a different autoclose char, after that autoclose is done it will add the char of the previously cancelled autoclose pair. Any way to fix this? I've attached a video of the behavior

Uploading Screen Recording 2024-06-29 at 6.19.39 AM.mov…

**Comment by altermo** [comment]
Replace the `if pair_insert then return end` with `if pair_insert then pair_insert=false return end` (in the `CursorMovedI` autocmd callback)

**Comment by sainttttt** [comment]
Works great! Thanks!
