### ISSUE TITLE
Delete comma after pair

### ISSUE THREAD

**Issue by sglkc** [altermo/ultimate-autopair.nvim#81]
Thanks for the awesome plugin, your solution to #46 is working flawlessly and saves a lot of repeated keystrokes. But now I wanted to delete the trailing comma if I delete a bracket pair.

|                 | Before | After |
|--------------|-----------|---------|
| Current   |   {\|},   |  \|,   |
| Expected |   {\|},  |   \|    |

Tried to make one myself, but have no idea how to make it trigger just on backspace or delete key :(

```lua
autocmd('TextChangedI', {
  callback = function()
    local cursor = vim.api.nvim_win_get_cursor(0)[2]
    local curr = vim.api.nvim_get_current_line():sub(cursor+1, cursor+1)
    local next = vim.api.nvim_get_current_line():sub(cursor+2, cursor+2)

    if (curr == ')' or curr == ']' or curr == '}') and next == ',' then
      local key = vim.api.nvim_replace_termcodes('<Delete>', true, false, true)
      vim.api.nvim_feedkeys(key, 'i', false)
    end
  end
})
```

Do you think it's possible with the help of this plugin?

**Comment by altermo** [comment]
This should work:
```lua
require('ultimate-autopair').setup{
  {'{','},',disable_start=true,disable_end=true,p=11},
  {'[','],',disable_start=true,disable_end=true,p=11},
  {'(','),',disable_start=true,disable_end=true,p=11},
}
```

**Comment by sglkc** [comment]
> This should work:
> 
> ```lua
> require('ultimate-autopair').setup{
>   {'{','},',disable_start=true,disable_end=true,p=11},
>   {'[','],',disable_start=true,disable_end=true,p=11},
>   {'(','),',disable_start=true,disable_end=true,p=11},
> }
> ```

Unfortunately it's only working if I delete from the right of the comma, I wanted it to delete from the middle of the brackets

**Comment by altermo** [comment]
Let's see your config. You're using `init` instead of `setup`, then replace your `init` with this one and it should work:
```lua
require'ultimate-autopair'.init({
    require'ultimate-autopair'.extend_default({
        {'{','},',disable_start=true,disable_end=true,p=11},
        {'[','],',disable_start=true,disable_end=true,p=11},
        {'(','),',disable_start=true,disable_end=true,p=11},
    }),
    {
        profile='raw',
        create_map(),
    }})
```

**Comment by sglkc** [comment]
Here's my full config [autopairs.lua](https://github.com/sglkc/dotfiles/blob/master/.config/nvim/lua/plugins/autopairs.lua)

With auto comma:

https://github.com/altermo/ultimate-autopair.nvim/assets/31957516/5c6f3eb3-fc97-416a-9df3-92e90a72a0a6



Clean config:

https://github.com/altermo/ultimate-autopair.nvim/assets/31957516/c4b5d022-245c-456c-b141-681d468a3552

**Comment by altermo** [comment]
I now understand why it isn't working: I only tested with empty documents and forgot that `{`,`},` would try to open pair detect which was incorrect.
So here's code that doesn't try to use any internal pair matching and just does the task:
```lua
local utils=require'ultimate-autopair.utils'
local function create_map()
  local m={}
  m.doc='ultimate-autopair backspace map'
  m.p=11
  m.check=function (o)
    if o.mode=='i' and vim.fn.keytrans(o.key)=='<BS>' and
      ({['(),']=1,['[],']=1,['{},']=1})[o.line:sub(o.col-1,o.col+1)] then
      return utils.create_act{{'delete',1,2}}
    end
  end
  m.get_map=function (mode) if mode=='i' then return {'<bs>'} end end
  return m
end
require'ultimate-autopair'.init({
  require'ultimate-autopair'.extend_default{},
  {profile='raw',create_map()},
})
```

**Comment by sglkc** [comment]
Just as expected, thank you very much
