### ISSUE TITLE
Suround vs Surround

### ISSUE THREAD

**Issue by mblarsen** [altermo/ultimate-autopair.nvim#86]
Isn't surround spelled with two `r`s?

Noticed my help had typos-lsp attached and complained

<img width="677" alt="image" src="https://github.com/altermo/ultimate-autopair.nvim/assets/247048/478e8452-130d-42b6-829e-4b2e381bff1a">

**Comment by altermo** [comment]
Yes, and it will be fixed in v0.7 (as I misspelled surround in the code, including configuration names, which means that this would be a breaking change)

**Comment by mblarsen** [comment]
> Yes, and it will be fixed in v0.7 (as I misspelled surround in the code, including configuration names, which means that this would be a breaking change)

Thought as much. Just wanted to make sure that you were aware 👍
