### ISSUE TITLE
[Bug] Pairing in Select mode doesn't work when LSP server loads

### ISSUE THREAD

**Issue by alexmozaidze** [altermo/ultimate-autopair.nvim#89]
# Problem

[Select mode] is used extensively in snippet plugins. Whenever you get to a checkpoint while expanding the snippet, a region of text is selected with Select mode, allowing the user to type whatever he wants instead of the highlighted text.

However, when inputting a pairing character in [Select mode] (like `"`), it does not get enclosed.

# Solution

Implement pairing for [Select mode].

# Reproduce

1. Select some text in Visual mode selection
2. Press `<c-g>` to switch to [Select mode]
3. Input `(`, `"` or any other pairing character
4. Watch it not getting paired

[Select mode]: https://neovim.io/doc/user/visual.html#Select

**Comment by altermo** [comment]
Can't reproduce bug.

<details><summary>Script which I used to try to reproduce</summary>

\
Create file `init.lua` with content:
```lua
vim.fn.system{'git','clone','https://github.com/altermo/ultimate-autopair.nvim'}
vim.opt.runtimepath:append('ultimate-autopair.nvim')
require('ultimate-autopair').setup{}
vim.api.nvim_input('ifoo<esc>vb<C-g>"')
```
And run in shell `nvim -u init.lua`

</details>

**Comment by alexmozaidze** [comment]
Yeah, I just checked it, and it seems to work fine. I did some experimenting and found out that the problem starts occurring when an LSP server finishes loading. Perhaps, the problem lies there? I will make a minimal reproduction later to test out where the problem lies precisely.

**Comment by alexmozaidze** [comment]
The behaviour seems to be inconsistent. It may be the problem with my lazy-loading on events, I changed it from `InsertEnter` to `ModeChanged *:[vi]` and it seems to work fine right now. I will close the issue, but if I find a way to consistently reproduce the bug, I will re-open.
