### ISSUE TITLE
Command Mode Inconsistent Behavior

### ISSUE THREAD

**Issue by 173brian** [altermo/ultimate-autopair.nvim#91]
This is an amazing plugin, thank you for your efforts!
When using a setup without the option "CmdlineEnter" while keeping the "InsertEnter" event trigger autopairs aren't added to the command input in command mode _until_ an insert event is triggered, after which autopairs are added even to the command input. It would appear that a function may need to be added to suspend autopair behavior after an insert event in case of setups that desire autopairs in insert mode but not command mode.

**Comment by altermo** [comment]
The option is part of the plugin manager (e.g. lazy) and not part of the plugin (e.g. ultimate-autopair) and has only the job of lazyloading, so making it interact with other things would be unintuitive.
In the README, setting this option is supposed to only be a recommendation of how to lazyload the plugin.

Also, to disable autopair in command mode, use `cmap=false`.
