### ISSUE TITLE
`"` shouldn't be auto-completed when typed after `@` in vimscript or cmdline

### ISSUE THREAD

**Issue by Bekaboo** [altermo/ultimate-autopair.nvim#95]
`"` shouldn't be auto-completed when typed after `@` in vimscript or cmdline because `@"` represents the unnamed register.

**Comment by altermo** [comment]
Added https://github.com/altermo/ultimate-autopair.nvim/commit/3d061253d4f827a39dff0c2575fc7356e79a7d26

**Comment by Bekaboo** [comment]
@altermo `"` is still auto-paired if `@` is not the first character in the current line:


https://github.com/user-attachments/assets/7a0bae7a-52d5-4726-951e-3e33b32f8a61

**Comment by altermo** [comment]
fixed

**Comment by Bekaboo** [comment]
Thanks for the quick fix!
