### ISSUE TITLE
State of the project...

### ISSUE THREAD

**Issue by svanharmelen** [altermo/ultimate-autopair.nvim#97]
Hi @altermo 👋🏻 

I've noticed the updated readme and was wondering if you could elaborate what this means for the project? Does it mean that the plugin "as is" will be maintained and community PRs will be reviewed/merged? Or does it mean the project is no longer actively used by the maintainer and maybe people should think about switching to another plugin?

Maybe its just a language thing (I'm not a native English speaker), but I was a bit unsure how to read it 😊  In any case thanks for the efforts you have put into this plugin!

Best,
Sander

**Comment by altermo** [comment]
I will (try to) fix any bugs and PRs will be reviewed/merged. I plan to add a few quality-of-life features, but the plugin is mostly "as is".

**Comment by svanharmelen** [comment]
Thanks for your reply! Keeping it "as is" but (best effort) maintained is more then enough for me to keep using the plugin (as I really like it) 👍🏻
