### ISSUE TITLE
Prevent autopairs when next char is not whitespace (or when the next char is a letter)?

### ISSUE THREAD

**Issue by svanharmelen** [altermo/ultimate-autopair.nvim#98]
Is there a generic way to prevent autopairs to insert when the next char is not whitespace (or maybe better, the next char is a letter)? Or is this something that is configured for each rule individually? And if the latter, can I then add something to the `config_internal_pairs` block? Thanks!

**Comment by altermo** [comment]
```lua
{
  extensions={alpha={after=true}},
}
```

**Comment by svanharmelen** [comment]
Thanks ❤️
