### ISSUE TITLE
Is there a way to prevent <BS> to delete both the opening and closing part of the pair?

### ISSUE THREAD

**Issue by svanharmelen** [altermo/ultimate-autopair.nvim#99]
After a fun day of updating and tweaking my setup I seem to have one annoyance left, and that is that backspace deletes the pair even if its empty (which I would like to prevent).

So I like the general behavior (al lot), but wonder if I can get it to do this:

`""| > bs > "|` so leaving the opening part, instead of what it does now (removing the whole pair): `""| > bs > |` 

This seems related to the fact there is noting in between the quotes as otherwise if doesn't remove the first quote:
`"something"| > bs > "something|`

**Comment by altermo** [comment]
I haven't yet added a general option to do this.
Here's a config (you can extend it with more ifs):
```lua
{
  extensions={cond={cond={function (_,o)
    if o.key~=vim.api.nvim_replace_termcodes('<bs>',true,true,true) then return true end
    if o.line:sub(o.col-2,o.col-1)=='""' then return false end
    return true
  end}}}
}
```

**Comment by svanharmelen** [comment]
Cool, thanks for that! That should get me going 👍🏻

**Comment by llakala** [comment]
Is there a way to generalize this solution to any pair?

**Comment by altermo** [comment]
Or I could just add an option to disable this (https://github.com/altermo/ultimate-autopair.nvim/commit/6a51446c2c8f09a7c207d2dc2aaa5bbbda36e093): `{ bs = { delete_from_end = false }}`

**Comment by llakala** [comment]
Thanks!!
